src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>RelatedWorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Work Order</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Player</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Sprint Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cradle Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Verizon Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verizon USB Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wifi Hotspot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <formula>Account.Primary_Contact__r.FirstName &amp; &apos; &apos; &amp; Account.Primary_Contact__r.LastName</formula>
        <label>Primary Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>BAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV &amp; PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV &amp; PC &amp; Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard 32 Touch Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard 40 Touch Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WR WiFi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WR WiFi - Sprint</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>PackageCode__c</fullName>
        <label>Package Code</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Type1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>Order ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedWorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Work Order</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShippingCity__c</fullName>
        <label>Shipping City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingPostalCode__c</fullName>
        <label>Shipping Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingState__c</fullName>
        <label>Shipping State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingStreet__c</fullName>
        <label>Shipping Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrackingNumber__c</fullName>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShipmentItem__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shipment Items</relationshipLabel>
        <relationshipName>ShipmentItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Items</relationshipLabel>
        <relationshipName>Shipment_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TrackingNumber__c</fullName>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Shipment Item</label>
    <nameField>
        <label>Shipment Item SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ShipmentTest.cls
@isTest
private class ShipmentTest {
	
	private static testMethod void testShipmentWithAccount() {
		Contact contact = new Contact();
		contact.FirstName = 'First Name';
		contact.LastName = 'Last Name';
		insert contact;
		Account account = new Account();
		account.Name = 'Account Name';
		account.Primary_Contact__c = contact.Id;
		insert account;

		Shipment shipment = new Shipment(account);

		system.assert(shipment.shipment.Account__c == account.Id);
		system.assert(shipment.shipment.RelatedWorkOrder__c == null);
	}

	private static testMethod void testShipmentWithAccountWithAssets() {
		Contact contact = new Contact();
		contact.FirstName = 'First Name';
		contact.LastName = 'Last Name';
		insert contact;
		Account account = new Account();
		account.Name = 'Account Name';
		account.Primary_Contact__c = contact.Id;
		insert account;
		Asset asset = new Asset();
		asset.AccountId = account.Id;
		asset.Name = 'Asset Name';
		asset.Status = 'Installed';
		insert asset;

		account = AccountService.getWithAssetsAndContactsById(account.Id, new List<String> {'BillingCity',
																							'BillingPostalCode',
																							'BillingState',
																							'BillingStateCode',
																							'BillingStreet',
																							'Name',
																							'Primary_Contact__c'}, new List<String> {'Name',
																																	 'Shipment__c',
																																	 'Status'}, new List<String> {'Id'});

		Shipment shipment = new Shipment(account);

		system.assert(shipment.shipment.Account__c == account.Id);
		system.assert(shipment.shipment.RelatedWorkOrder__c == null);
		system.assert(ListUtils.isNotNullOrEmpty(shipment.returnItems));
	}

	private static testMethod void testShipmentWithAccountAndCase() {
		Contact contact = new Contact();
		contact.FirstName = 'First Name';
		contact.LastName = 'Last Name';
		insert contact;
		Account account = new Account();
		account.Name = 'Account Name';
		account.Primary_Contact__c = contact.Id;
		insert account;
		Case workOrder = new Case();
		workOrder.AccountId = account.Id;
		insert workOrder;

		Shipment shipment = new Shipment(account, workOrder);

		system.assert(shipment.shipment.Account__c == account.Id);
		system.assert(shipment.shipment.RelatedWorkOrder__c == workOrder.Id);
	}

	private static testMethod void testLoadShipment() {
		Contact contact = new Contact();
		contact.FirstName = 'First Name';
		contact.LastName = 'Last Name';
		insert contact;
		Account account = new Account();
		account.Name = 'Account Name';
		account.Primary_Contact__c = contact.Id;
		insert account;
		Shipment__c shipmentToLoad = new Shipment__c();
 		shipmentToLoad.Account__c = account.Id;
 		shipmentToLoad.OrderId__c = '12345';
		insert shipmentToLoad;
		Product2 product = new Product2();
		product.IsActive = true;
		product.Name = 'Product Name';
		product.ProductCode = 'Product Code';
		insert product;
		ShipmentItem__c shipmentItem = new ShipmentItem__c();
		shipmentItem.Product__c = product.Id;
		shipmentItem.Quantity__c = 1;
		shipmentItem.Shipment__c = shipmentToLoad.Id;
		insert shipmentItem;

		Shipment shipment = new Shipment(account);
		system.assert(shipment.shipmentItems == null || shipment.shipmentItems.isEmpty());

		shipmentToLoad = ShipmentService.getWithShipmentItemsByOrderId('12345', new List<String> {'Account__c',
																								  'OrderId__c'}, new List<String> {'Product__c',
																								  								   'Product__r.Name',
																								  								   'Product__r.ProductCode',
																								  								   'Quantity__c',
																								  								   'TrackingNumber__c',
																								  								   'Type__c'});
		shipment.load(shipmentToLoad, null);
		system.assert(shipment.shipmentItems != null && !shipment.shipmentItems.isEmpty());
	}

	private static testMethod void testLoadShipmentWithAssets() {
		Contact contact = new Contact();
		contact.FirstName = 'First Name';
		contact.LastName = 'Last Name';
		insert contact;
		Account account = new Account();
		account.Name = 'Account Name';
		account.Primary_Contact__c = contact.Id;
		insert account;
		Asset asset = new Asset();
		asset.AccountId = account.Id;
		asset.Name = 'Asset Name';
		asset.Status = 'Installed';
		insert asset;
		Shipment__c shipmentToLoad = new Shipment__c();
 		shipmentToLoad.Account__c = account.Id;
 		shipmentToLoad.OrderId__c = '12345';
		insert shipmentToLoad;
		Product2 product = new Product2();
		product.IsActive = true;
		product.Name = 'Product Name';
		product.ProductCode = 'Product Code';
		insert product;
		ShipmentItem__c shipmentItem = new ShipmentItem__c();
		shipmentItem.Product__c = product.Id;
		shipmentItem.Quantity__c = 1;
		shipmentItem.Shipment__c = shipmentToLoad.Id;
		insert shipmentItem;

		Shipment shipment = new Shipment(account);
		system.assert(shipment.shipmentItems == null || shipment.shipmentItems.isEmpty());

		account = AccountService.getWithAssetsAndContactsById(account.Id, new List<String> {'BillingCity',
																							'BillingPostalCode',
																							'BillingState',
																							'BillingStateCode',
																							'BillingStreet',
																							'Name',
																							'Primary_Contact__c'}, new List<String> {'Name',
																																	 'Shipment__c',
																																	 'Status'}, new List<String> {'Id'});
		shipmentToLoad = ShipmentService.getWithShipmentItemsByOrderId('12345', new List<String> {'Account__c',
																								  'OrderId__c'}, new List<String> {'Product__c',
																								  								   'Product__r.Name',
																								  								   'Product__r.ProductCode',
																								  								   'Quantity__c',
																								  								   'TrackingNumber__c',
																								  								   'Type__c'});
		shipment.load(shipmentToLoad, new List<Asset> {asset});
		system.assert(shipment.shipmentItems != null && !shipment.shipmentItems.isEmpty());
		system.assert(ListUtils.isNotNullOrEmpty(shipment.returnItems));
	}

	private static testMethod void testClear() {
		Contact contact = new Contact();
		contact.FirstName = 'First Name';
		contact.LastName = 'Last Name';
		insert contact;
		Account account = new Account();
		account.Name = 'Account Name';
		account.Primary_Contact__c = contact.Id;
		insert account;
		Product2 product = new Product2();
		product.IsActive = true;
		product.Name = 'Product Name';
		product.ProductCode = 'Product Code';
		insert product;

		Shipment shipment = new Shipment(account);

		shipment.shipment.ShippingStreet__c = 'Second Street';
		shipment.shipment.ShippingCity__c = 'Second City';
		shipment.shipment.ShippingState__c = 'Second State';
		shipment.shipment.ShippingPostalCode__c = '12345';

		shipment.addProducts(new List<String> {'Product Code'});

		shipment.clear(account, null);

		system.assert(shipment.shipment.ShippingStreet__c != 'Second Street');
		system.assert(shipment.shipment.ShippingCity__c != 'Second City');
		system.assert(shipment.shipment.ShippingState__c != 'Second State');
		system.assert(shipment.shipment.ShippingPostalCode__c != '12345');
		system.assert(shipment.shipmentItems == null || shipment.shipmentItems.isEmpty());
	}

	private static testMethod void testClearWithReturnItems() {
		Contact contact = new Contact();
		contact.FirstName = 'First Name';
		contact.LastName = 'Last Name';
		insert contact;
		Account account = new Account();
		account.Name = 'Account Name';
		account.Primary_Contact__c = contact.Id;
		insert account;
		Asset asset = new Asset();
		asset.AccountId = account.Id;
		asset.Name = 'Asset Name';
		asset.Status = 'Installed';
		insert asset;
		Shipment__c shipmentToLoad = new Shipment__c();
 		shipmentToLoad.Account__c = account.Id;
 		shipmentToLoad.OrderId__c = '12345';
		insert shipmentToLoad;
		Product2 product = new Product2();
		product.IsActive = true;
		product.Name = 'Product Name';
		product.ProductCode = 'Product Code';
		insert product;
		ShipmentItem__c shipmentItem = new ShipmentItem__c();
		shipmentItem.Product__c = product.Id;
		shipmentItem.Quantity__c = 1;
		shipmentItem.Shipment__c = shipmentToLoad.Id;
		insert shipmentItem;

		account = AccountService.getWithAssetsAndContactsById(account.Id, new List<String> {'BillingCity',
																							'BillingPostalCode',
																							'BillingState',
																							'BillingStateCode',
																							'BillingStreet',
																							'Name',
																							'Primary_Contact__c'}, new List<String> {'Name',
																																	 'Shipment__c',
																																	 'Status'}, new List<String> {'Id'});
		Shipment shipment = new Shipment(account);
		system.assert(ListUtils.isNotNullOrEmpty(shipment.returnItems));
		for (Shipment.ReturnItem returnItem : shipment.returnItems) {
			returnItem.returning = true;
		}

		shipment.clear(account, null);
		for (Shipment.ReturnItem returnItem : shipment.returnItems) {
			system.assert(!returnItem.returning);
		}
	}

	private static testMethod void testAddPackage() {
		Contact contact = new Contact();
		contact.FirstName = 'First Name';
		contact.LastName = 'Last Name';
		insert contact;
		Account account = new Account();
		account.Name = 'Account Name';
		account.Primary_Contact__c = contact.Id;
		insert account;
		Product2 product = new Product2();
		product.IsActive = true;
		product.Name = 'Product Name';
		product.ProductCode = 'Product Code';
		insert product;
		Pricebook2 productPackage = new Pricebook2();
		productPackage.IsActive = true;
		productPackage.Name = 'Product Package';
		productPackage.PackageCode__c = 'Package Code';
		insert productPackage;
		PricebookEntry standardEntry = new PricebookEntry();
		standardEntry.Pricebook2Id = Test.getStandardPricebookId();
		standardEntry.Product2Id = product.Id;
		standardEntry.Quantity__c = 1;
		standardEntry.IsActive = true;
		standardEntry.UnitPrice = 0;
		insert standardEntry;
		PricebookEntry entry = new PricebookEntry();
		entry.Pricebook2Id = productPackage.Id;
		entry.Product2Id = product.Id;
		entry.Quantity__c = 1;
		entry.IsActive = true;
		entry.UnitPrice = 0;
		insert entry;

		Shipment shipment = new Shipment(account);
		shipment.addPackage('Package Code');

		system.assert(shipment.shipmentItems != null && !shipment.shipmentItems.isEmpty());
	}

	private static testMethod void testAddPackage2() {
		Contact contact = new Contact();
		contact.FirstName = 'First Name';
		contact.LastName = 'Last Name';
		insert contact;
		Account account = new Account();
		account.Name = 'Account Name';
		account.Primary_Contact__c = contact.Id;
		insert account;
		Product2 product = new Product2();
		product.IsActive = true;
		product.Name = 'Product Name';
		product.ProductCode = 'Product Code';
		insert product;
		Pricebook2 productPackage = new Pricebook2();
		productPackage.IsActive = true;
		productPackage.Name = 'Product Package';
		productPackage.PackageCode__c = 'Package Code';
		insert productPackage;
		PricebookEntry standardEntry = new PricebookEntry();
		standardEntry.Pricebook2Id = Test.getStandardPricebookId();
		standardEntry.Product2Id = product.Id;
		standardEntry.Quantity__c = 1;
		standardEntry.IsActive = true;
		standardEntry.UnitPrice = 0;
		insert standardEntry;
		PricebookEntry entry = new PricebookEntry();
		entry.Pricebook2Id = productPackage.Id;
		entry.Product2Id = product.Id;
		entry.Quantity__c = 1;
		entry.IsActive = true;
		entry.UnitPrice = 0;
		insert entry;

		Shipment shipment = new Shipment(account);

		shipment.addProducts(new List<String> {'Product Code'});
		shipment.addPackage('Package Code');

		system.assert(shipment.shipmentItems.get('Product Code').quantity == 2);
	}

	private static testMethod void testAddProducts() {
		Contact contact = new Contact();
		contact.FirstName = 'First Name';
		contact.LastName = 'Last Name';
		insert contact;
		Account account = new Account();
		account.Name = 'Account Name';
		account.Primary_Contact__c = contact.Id;
		insert account;
		Product2 product = new Product2();
		product.IsActive = true;
		product.Name = 'Product Name';
		product.ProductCode = 'Product Code';
		insert product;

		Shipment shipment = new Shipment(account);

		shipment.addProducts(new List<String> {'Product Code'});
		system.assert(shipment.shipmentItems.get('Product Code') != null);

		shipment.addProducts(new List<String> {'Product Code'});
		system.assert(shipment.shipmentItems.get('Product Code').quantity == 2);
	}

	private static testMethod void testRemoveProduct() {
		Contact contact = new Contact();
		contact.FirstName = 'First Name';
		contact.LastName = 'Last Name';
		insert contact;
		Account account = new Account();
		account.Name = 'Account Name';
		account.Primary_Contact__c = contact.Id;
		insert account;
		Product2 product = new Product2();
		product.IsActive = true;
		product.Name = 'Product Name';
		product.ProductCode = 'Product Code';
		insert product;

		Shipment shipment = new Shipment(account);

		shipment.addProducts(new List<String> {'Product Code'});
		shipment.remove('Product Code');

		system.assert(shipment.shipmentItems.get('Product Code') == null);
		system.assert(ListUtils.isNullOrEmpty(shipment.shipmentItemsList));
	}
}