src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMHID__c</fullName>
        <externalId>true</externalId>
        <label>CMH ID</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DMA_Zip_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DMA Zip Code</label>
        <referenceTo>Zip_Code_Data__c</referenceTo>
        <relationshipLabel>Accounts (DMA Zip Code)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed_Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed unscheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending IT coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending competitor removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending line drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled - Competitor Removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial install plays content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial install no content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial install DVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Repair - no content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Repair - playing content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVD Site - Pending Repair/Awaiting Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uninstalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold Delayed Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed Delayed Installation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>offset_st__c</fullName>
        <formula>DMA_Zip_Code__r.OFFSET_ST__c</formula>
        <label>OFFSET ST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped to Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damaged - At Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped from Supplier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chicago Liquidators Warehouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ContextMedia Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <controllingField>Make__c</controllingField>
            <picklistValues>
                <fullName>20LS7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LT560C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LV255C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250U - Sprint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LC7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LD352C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LH20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LT560C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LC7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD452B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LH20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LN541C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LT560E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LV255C - LED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD450C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD452B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LT560E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD450C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD452B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LN541C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LT560E</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Shipping_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipping Order</label>
        <referenceTo>Shipping_Order__c</referenceTo>
        <relationshipLabel>Equipment</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>OFFSET_ST__c</fullName>
        <formula>Account.DMA_Zip_Code__r.OFFSET_ST__c</formula>
        <label>OFFSET ST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Unscheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending IT coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending line drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed, but IT issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deinstalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled (only for LO)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <picklistValues>
                <fullName>AOpen DE 945CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherlock-D510</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherlock-D525</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seneca - D525</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technovare-2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mediawave-ION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>598U - Sprint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20LS7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LC7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LH20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LC7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NU DVD PDP-100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CODY DVD209</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sylvania DVD Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emerson DVD Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LH20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42PJ350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD450C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD450C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD452B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LD352C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LV255C</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Shipping_Order__c.object
<CustomObject>
    <description>Shipping Order History</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipping Orders</relationshipLabel>
        <relationshipName>Shipping_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CMHID__c</fullName>
        <formula>Related_Work_Order__r.CMH_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CMHID</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offset_DST__c</fullName>
        <formula>Account__r.OFFSET_DST_c__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offset DST</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offset_ST__c</fullName>
        <formula>Account__r.offset_st__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offset ST</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Shipping Order</label>
    <nameField>
        <displayFormat>ShippingOrder-{000000}</displayFormat>
        <label>Shipping Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Zip_Code_Data__c.object
<CustomObject>
    <description>Created by the Cloud Converter from http://ModelMetrics.com</description>
    <fields>
        <fullName>OFFSET_DST__c</fullName>
        <description>UTC Offset Daylight Savings Time</description>
        <inlineHelpText>The Daylights Savings Time offset from UTC</inlineHelpText>
        <label>OFFSET DST</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OFFSET_ST__c</fullName>
        <description>UTC Offset for Standard time</description>
        <inlineHelpText>The Standard Time offset from UTC</inlineHelpText>
        <label>OFFSET ST</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Zip Code Data</label>
    <nameField>
        <label>DMA Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_ProductUpdate.cls
@isTest (SeeAllData=false)
public class Test_ProductUpdate {
public static testMethod void method1(){
Product2 prd1=new Product2(name='testprd1');
Product2 prd2=new Product2(name='testprd2');
insert prd1;
insert prd2;

Zip_Code_Data__c zcode=new Zip_Code_Data__c(Name='123',OFFSET_DST__c=-1,OFFSET_ST__c=-1);
insert zcode;
Account acc=new Account(name='test',DMA_Zip_Code__c=zcode.id,stage__c='Waitlist',CMHID__c=1234);
insert acc;
Account acc1=new Account(name='ContextMedia Inventory',DMA_Zip_Code__c=zcode.id,stage__c='Waitlist',CMHID__c=1234);
insert acc1;
Account acc2=new Account(name='ContextMedia Retired Inventory',DMA_Zip_Code__c=zcode.id,stage__c='Waitlist',CMHID__c=1234);
insert acc2;
Asset ast1=new Asset(name='test1',Model__c='20LS7DC',product2id=prd1.id,accountid=acc1.id,Location__c='Warehouse');
insert ast1;
Asset ast2=new Asset(name='test2',Model__c='20LS7DC',product2id=prd1.id,accountid=acc1.id,Location__c='Warehouse');
insert ast2;
list<recordtype> rt=new List<recordtype>();
List<Recordtype> rtype=[select id from recordtype where name='Shipping Order' and sobjecttype='Shipping_Order__c']; 
rt=[select id from recordtype where sobjecttype='Case' and name='Work Orders'];
Case testcase=new case(account=acc,status='new',type='Repair',recordtypeid=rt[0].id);
insert testcase;
Date myDate = date.newinstance(2014,07,20);
Shipping_order__c so = new Shipping_order__c (Account__c=acc.id,RecordTypeid=rtype[0].id,Type__c='Shipping Order',RequestedDateofArrival__c=myDate,Related_Work_Order__c=testcase.id);
Shipping_order__c so2 = new Shipping_order__c (Account__c=acc.id,RecordTypeid=rtype[0].id,Type__c='Shipping Order',RequestedDateofArrival__c=myDate,Related_Work_Order__c=testcase.id);
insert so2;
insert so;
ast2.accountid=acc.id;
ast2.Location__c='Retired';
ast2.Shipping_Order__c=so.id;
ast2.accountid=acc2.id;
update ast2;
ast2.accountid=acc2.id;
update ast2;
ast2.product2id=prd2.id;
update ast2;
ast2.Shipping_Order__c=so2.id;
update ast2;
ast2.Shipping_Order__c=null;
update ast2;
ast2.accountid=acc1.id;
update ast2;
ast1.product2id=prd2.id;
update ast1;
delete ast1;
ast2.accountid=acc.id;
update ast2;
delete ast2;



    }// end of method.
}// end of class.