src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMHID__c</fullName>
        <externalId>true</externalId>
        <label>CMH ID</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DMA_Zip_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DMA Zip Code</label>
        <referenceTo>Zip_Code_Data__c</referenceTo>
        <relationshipLabel>Accounts (DMA Zip Code)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Network__c</fullName>
        <description>Used to denote the requested content that a clinic would get if it were to become a member. Formerly known as &quot;Network&quot;.</description>
        <label>Content Requested</label>
        <picklist>
            <picklistValues>
                <fullName>Allergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endocrinology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gastroenterology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infectious Disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neurology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obstetrics and Gynecology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ophthalmology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optometry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rheumatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urology</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <formula>DMA_Zip_Code__r.Timezone__c</formula>
        <label>Time Zone</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Installation_Status__c</fullName>
        <label>Installation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>InstalledDate__c</fullName>
        <label>Installed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Player</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Sprint Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cradle Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Verizon Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verizon USB Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wifi Hotspot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <formula>Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LatestServiceDateEnd__c</fullName>
        <label>Latest Service Date - End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <formula>Account.Primary_Contact__r.FirstName &amp; &apos; &apos; &amp; Account.Primary_Contact__r.LastName</formula>
        <label>Primary Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>BAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV &amp; PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV &amp; PC &amp; Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard 32 Touch Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard 40 Touch Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WR WiFi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WR WiFi - Sprint</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Cable Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Deinstall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Outlet Locks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Line Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Device Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Deinstall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Player Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tech Only Dispatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Troubleshooting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV &amp; Tablet Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard Swap</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Work_Orders</fullName>
        <active>true</active>
        <businessProcess>Work Orders</businessProcess>
        <description>Blackout, Deinstallation, Install Brochures, Line Installation, New Installation, Relocation, Repair, Site Survey, Upgrade and Competitor Swap Install</description>
        <label>Work Orders</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead_time__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Map of zip code to lead time</description>
    <fields>
        <fullName>Lead_time__c</fullName>
        <label>Lead time</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Lead Time</label>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Box__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Box</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Type1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>AMDelivery__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AM Delivery</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AccountName__c</fullName>
        <formula>Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CmhId__c</fullName>
        <formula>TEXT(Account__r.CMHID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cmh Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpediteReason__c</fullName>
        <label>Expedite Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Avoid Significant Install Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prevent Deinstall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quick Revisit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>Order ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestedDateOfArrival__c</fullName>
        <label>Requested Date of Arrival</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RequestedPickupDate__c</fullName>
        <label>Requested Pick-Up Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShippedDate__c</fullName>
        <label>Shipped Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Shipped__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Shipped</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ShippingCity__c</fullName>
        <label>Shipping City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isExpedited__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expedited</label>
        <type>Checkbox</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseDetailsController.cls
public with sharing class CaseDetailsController extends CaseDetailsActions {
	private static final String CASEx = 'Case';
	public Case thisCase {get;set;}
	public Account account {get;set;}

	public Shipment shipment {get;set;}
	public Contact shipmentContact {get;set;}
	public List<Shipment__c> shipments {get;set;}

	//View related things.
	public Boolean hasErrors { get { return ApexPages.hasMessages(ApexPages.Severity.ERROR);} }
	public Boolean showReceivingItems { get { return ListUtils.isNotNullOrEmpty(shipment.returnItems);} }
	public Boolean showShipments { get { return thisCase.RecordType.Name == new Constants.CaseRecordTypes().WORK_ORDERS && thisCase.AccountId != null;} }
	public Boolean showShipmentItems { get { return shipment.shipmentItems!= null && !shipment.shipment.Shipped__c && !shipment.shipmentItems.isEmpty();} }
	public Boolean showShipmentPackages { get { return shipment.shipment != null && shipment.shipment.Shipped__c;} }
	public Boolean showShipmentMissingTrackingItems { get { return shipment.shipmentItems != null && shipment.shipment.Shipped__c && !shipment.shipmentItems.isEmpty();} }
	public Boolean showShipmentHistory { get { return ListUtils.isNotNullOrEmpty(shipments);} }
	public String selectedPackage {get;set;}
	public List<String> selectedProducts {get;set;}
	public List<String> productCodesToHighlight {get;set;}
	public Integer leadTimeInDays {get;set;}
	public List<String> availableDays {get;set;}
	public List<String> expediteDays {get;set;}
	public String serializedDays { get { return JSON.serialize(availableDays); } }
	public String serializedExpediteDays { get { return JSON.serialize(expediteDays); } }
	public String serializedCodes { get { return JSON.serialize(productCodesToHighlight);} }

	public CaseDetailsController(ApexPages.StandardController standardController) {
		standardController.addFields(new List<String> {'AccountId',
													   'CaseNumber',
													   'ContactId',
													   'Id',
													   'LatestServiceDateEnd__c',
													   'Product__c',
													   'RecordType.Name',
													   'Service__c',
													   'Status',
													   'Subject',
													   'Type'});
		thisCase = (Case)standardController.getRecord();
		if (showShipments) {
			account = AccountService.getWithAssetsAndContactsById(thisCase.AccountId, new List<String> {'BillingCity',
																										'BillingPostalCode',
																										'BillingState',
																										'BillingStateCode',
																									 	'BillingStreet',
																									 	'CMHID__c',
																									 	'DMA_Zip_Code__c',
																										'Id',
																										'Name',
																										'Network__c',
																									 	'Time_Zone__c'},
																					  new List<String> {'Id',
																				   						'Installation_Status__c',
																				   						'InstalledDate__c',
																				  						'Name',
																				  						'Product2.Box__r.ProductCode',
																				  						'Shipment__c',
																				  						'Status',
																				  					 	'Type__c'},
																					  new List<String> {'Email',
																				  						'FirstName',
																				  						'Id',
																				  						'LastName',
																				  						'Phone',
																				  						'Primary_Contact__c'});
			shipment = new Shipment(account, thisCase);
			refreshContact();
			loadShipments();
			Map<String, Lead_Time__c> leadTimes = Lead_Time__c.getAll();
			if (account.BillingPostalCode == null) {

			}
			else {
				leadTimeInDays = leadTimes.get(account.BillingPostalCode.split('-')[0]) == null ? 1 : Integer.valueOf(leadTimes.get(account.BillingPostalCode.split('-')[0]).Lead_Time__c);
				system.debug('lead time: ' + leadTimeInDays);
				system.debug('the time: ' + Datetime.now().hour());
				if (Datetime.now().hour() >= 17) {
					leadTimeInDays = leadTimeInDays + 1;
					system.debug('new lead time: ' + leadTimeInDays);
				}
			}
			availableDays = BusinessHoursService.getAvailableShippingDays(180);
			expediteDays = new List<String>();
			for (Integer i = 0; i < leadTimeInDays; i++) {
				expediteDays.add(availableDays[i]);
			}
		}
	}

	public void loadShipments() {
		shipments = ShipmentService.getWithShipmentItemsAssetsShipmentPackagesByCaseId(thisCase.Id, new List<String> {'Account__c',
																													  'AccountName__c',
																													  'AMDelivery__c',
																													  'CmhId__c',
																													  'Company__c',
																													  'Contact__c',
																													  'CreatedDate',
																													  'ExpediteReason__c',
																													  'Id',
																													  'isExpedited__c',
																													  'Name',
																													  'OrderId__c',
																													  'RequestedDateOfArrival__c',
																													  'RequestedPickupDate__c',
																													  'Shipped__c',
																													  'ShippedDate__c',
																													  'ShippingCity__c',
																													  'ShippingPostalCode__c',
																													  'ShippingState__c',
																													  'ShippingStreet__c',
																													  'ShippingStreet2__c',
																													  'TrackingNumber__c'},
																								    new List<String> {'Name',
																								  					  'Product__c',
																								  					  'Product__r.Name',
																								  					  'Product__r.ProductCode',
																													  'Quantity__c',
																													  'TrackingNumber__c',
																													  'Type__c'},
																								    new List<String> {'Id',
																							   						  'Installation_Status__c',
																							   						  'InstalledDate__c',
																							  						  'Name',
																							  						  'Product2.Box__r.ProductCode',
																							  						  'Shipment__c',
																							  						  'Status',
																							  					 	  'Type__c'},
																						  		    new List<String> {'ActivityDate__c',
																										  		   	  'Id',
																										  		   	  'LeftAtLocation__c',
																						  		   					  'ProductCode__c',
																						  		   					  'ScheduledDeliveryDate__c',
																						  		   					  'SignedForName__c',
																						  							  'Status__C',
																						  							  'TrackingNumber__c'});
	}

	public void addBox() {
		String boxId = ApexPages.currentPage().getParameters().get('product');
		productCodesToHighlight = new List<String>();
		if (boxId == '') {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'The appropriate box for this asset was unable to be determined. Please add the box and a receiving label manually.'));
		}
		else {
			productCodesToHighlight = shipment.addProducts(new List<String> {boxId, 'LAB101'});
		}
	}

	public void addPackage() {
		productCodesToHighlight = new List<String>();
		if (selectedPackage == null || selectedPackage == '') {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select a package.'));
		}
		else {
			productCodesToHighlight = shipment.addPackage(selectedPackage);
		}
	}

	public void addProducts() {
		productCodesToHighlight = new List<String>();
		if (ListUtils.isNullOrEmpty(selectedProducts)) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select one or more products.'));
		}
		else {
			productCodesToHighlight = shipment.addProducts(selectedProducts);
		}
	}

	public void refreshContact() {
		if (shipment.shipment.Contact__c != null) {
			try {
				shipmentContact = ContactService.getById(shipment.shipment.Contact__c, new List<String> {'Email',
																										 'FirstName',
																										 'LastName',
																										 'Phone'});
			}
			catch(QueryException ex) {
				shipmentContact = null;
			}
		}
		else {
			shipmentContact = null;
		}
	}

	public void removeProduct() {
		String productId = ApexPages.currentPage().getParameters().get('product');
		try {
			shipment.remove(productId);
		}
		catch(Exception ex) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
		}
	}

	public void saveShipment() {
		try {
			if (shipment.shipment.Contact__c != null) {
				shipmentContact = ContactService.getById(shipment.shipment.Contact__c, new List<String> {'Email',
																										 'FirstName',
																										 'LastName',
																										 'Phone'});
			}
			List<String> errors = ShipmentService.validate(shipment, account, shipmentContact);
			if (ListUtils.isNotNullOrEmpty(errors)) {
				for (String error : errors) {
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, error));
				}
			}
			else {
				shipment.shipment.EstimatedShipDate__c = BusinessHoursService.getEstimatedShipDate(shipment.shipment, leadTimeInDays);
				if (shipment.shipment.OrderId__c == null) {
					//Increment the return label SKU if it exists and add 1 if it doesn't.
					if (shipment.shipmentItems.get(new Constants.ProductCodes().RETURN_LABEL) != null) {
						shipment.shipmentItems.get(new Constants.ProductCodes().RETURN_LABEL).quantity++;
					}
					else {
						shipment.addProducts(new List<String> {new Constants.ProductCodes().RETURN_LABEL});
					}
					
					Long orderId = Crypto.getRandomLong();
					shipment.shipment.OrderId__c = String.valueOf(orderId < 0 ? orderId * -1 : orderId);
					ShipmentDelegate.putOrder(shipment, account, shipmentContact);
					ShipmentService.save(shipment);
					shipments.add(shipment.shipment);
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'The order was saved successfully!'));
				}
				else {
					ShipmentDelegate.updateOrder(shipment, account, shipmentContact);
					ShipmentService.save(shipment);
					shipments.add(shipment.shipment);
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'The order was updated successfully!'));
				}
				loadShipments();
				clearShipment();
				shipment.refreshReturnItems(AssetService.getByAccountId(account.Id, new List<String> {'Id',
																			   						  'Installation_Status__c',
																			   						  'InstalledDate__c',
																			  						  'Name',
																			  						  'Product2.Box__r.ProductCode',
																			  						  'Shipment__c',
																			  						  'Status',
																			  					 	  'Type__c'}));
			}
		}
		catch(Exception ex) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
		}
	}

	public void editShipment() {
		String orderId = ApexPages.currentPage().getParameters().get('orderId');
		system.debug('Order Id: ' + orderId);
		for (Shipment__c order : shipments) {
			if (order.Id == orderId) {
				shipment.load(order, account.Assets);
				refreshContact();
			}
		}
	}

	public void cancelShipment() {
		String orderId = ApexPages.currentPage().getParameters().get('orderId');
		try {
			if (orderId != null && orderId != '') {
				HttpRequestResult cancelRequestResult = ShipmentDelegate.cancelOrder(orderId);
				if (cancelRequestResult.success) {
					for (Integer i = 0; i < shipments.size(); i++) {
						if (shipments[i].OrderId__c == orderId) {
							delete shipments[i];
							shipments.remove(i);
							shipment.refreshReturnItems(AssetService.getByAccountId(account.Id, new List<String> {'Id',
																						   						  'Installation_Status__c',
																						   						  'InstalledDate__c',
																						  						  'Name',
																						  						  'Product2.Box__r.ProductCode',
																						  						  'Shipment__c',
																						  						  'Status',
																						  					 	  'Type__c'}));
							break;
						}
					}
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, cancelRequestResult.userFriendlyResultMessage));
				} else {
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, cancelRequestResult.userFriendlyResultMessage));
				}
			}
		}
		catch(Exception ex) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
		}
	}

	public void clearShipment() {
		shipment.clear(account, thisCase);
	}
}