src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMHID__c</fullName>
        <externalId>true</externalId>
        <label>CMH ID</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DMA_Zip_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DMA Zip Code</label>
        <referenceTo>Zip_Code_Data__c</referenceTo>
        <relationshipLabel>Accounts (DMA Zip Code)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed_Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed unscheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending IT coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending competitor removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending line drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled - Competitor Removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial install plays content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial install no content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial install DVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Repair - no content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Repair - playing content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVD Site - Pending Repair/Awaiting Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uninstalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold Delayed Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed Delayed Installation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>offset_st__c</fullName>
        <formula>DMA_Zip_Code__r.OFFSET_ST__c</formula>
        <label>OFFSET ST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <controllingField>Make__c</controllingField>
            <picklistValues>
                <fullName>20LS7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LT560C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LV255C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250U - Sprint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LC7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LD352C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LH20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LT560C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LC7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD452B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LH20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LN541C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LT560E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LV255C - LED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD450C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD452B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LT560E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD450C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD452B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LN541C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LT560E</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <picklistValues>
                <fullName>AOpen DE 945CD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherlock-D510</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sherlock-D525</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seneca - D525</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technovare-2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mediawave-ION</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>598U - Sprint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20LS7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LC7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LH20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LC7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NU DVD PDP-100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CODY DVD209</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sylvania DVD Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emerson DVD Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LH20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42PJ350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD450C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD450C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD452B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LD352C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LV255C</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Zip_Code_Data__c.object
<CustomObject>
    <description>Created by the Cloud Converter from http://ModelMetrics.com</description>
    <fields>
        <fullName>OFFSET_DST__c</fullName>
        <description>UTC Offset Daylight Savings Time</description>
        <inlineHelpText>The Daylights Savings Time offset from UTC</inlineHelpText>
        <label>OFFSET DST</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OFFSET_ST__c</fullName>
        <description>UTC Offset for Standard time</description>
        <inlineHelpText>The Standard Time offset from UTC</inlineHelpText>
        <label>OFFSET ST</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Zip Code Data</label>
    <nameField>
        <label>DMA Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_Datefieldupdate.cls
@isTest (SeeAllData=false)
public class Test_Datefieldupdate {
public static testMethod void method1(){
Product2 prd1=new Product2(name='testprd1');
Product2 prd2=new Product2(name='testprd2');
insert prd1;
insert prd2;
Zip_Code_Data__c zcode=new Zip_Code_Data__c(Name='123',OFFSET_DST__c=-1,OFFSET_ST__c=-1);
insert zcode;
Account acc=new Account(name='test',DMA_Zip_Code__c=zcode.id,stage__c='Waitlist',CMHID__c=1234);
insert acc;
Account acc1=new Account(name='ContextMedia Inventory',DMA_Zip_Code__c=zcode.id,stage__c='Waitlist',CMHID__c=1234);
insert acc1;
Account acc2=new Account(name='ContextMedia Retired Inventory',DMA_Zip_Code__c=zcode.id,stage__c='Waitlist',CMHID__c=1234);
insert acc2;
Asset ast1=new Asset(name='test1',Model__c='20LS7DC',product2id=prd1.id,accountid=acc1.id);
insert ast1;
Asset ast2=new Asset(name='test2',Model__c='20LS7DC',product2id=prd1.id,accountid=acc1.id);
insert ast2;
ast2.accountid=acc.id;
update ast2;
ast2.accountid=acc2.id;
update ast2;


    }// end of method.
}// end of class.