src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMHID__c</fullName>
        <externalId>true</externalId>
        <label>CMH ID</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Network__c</fullName>
        <description>Used to denote the requested content that a clinic would get if it were to become a member. Formerly known as &quot;Network&quot;.</description>
        <label>Content Requested</label>
        <picklist>
            <picklistValues>
                <fullName>Allergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endocrinology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gastroenterology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infectious Disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neurology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obstetrics and Gynecology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ophthalmology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optometry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rheumatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urology</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed_Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed unscheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending IT coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending competitor removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending line drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled - Competitor Removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial install plays content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial install no content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial install DVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Repair - no content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Repair - playing content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVD Site - Pending Repair/Awaiting Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uninstalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold Delayed Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed Delayed Installation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <formula>DMA_Zip_Code__r.Timezone__c</formula>
        <label>Time Zone</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Member_Services</fullName>
        <active>true</active>
        <label>Member Services</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>ClinicExamRoom__c</fullName>
        <label>Clinic Exam Room</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Installation_Status__c</fullName>
        <label>Installation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>InstalledDate__c</fullName>
        <label>Installed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MountType__c</fullName>
        <label>Mount Type</label>
        <picklist>
            <picklistValues>
                <fullName>Floor Chair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floor Standing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wall Ball Joint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wall Tethered</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speciality__c</fullName>
        <label>Speciality</label>
        <picklist>
            <picklistValues>
                <fullName>Combo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diabetes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Heart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neurology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rheum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rheum No Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship - GI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship - Neuro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship - PCP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sponsorship - Rheum</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Player</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Sprint Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cradle Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Verizon Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verizon USB Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wifi Hotspot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Volume__c</fullName>
        <label>TTL Volume</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <formula>Account.Primary_Contact__r.FirstName &amp; &apos; &apos; &amp; Account.Primary_Contact__r.LastName</formula>
        <label>Primary Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Unscheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending IT coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending line drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed, but IT issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deinstalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled (only for LO)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Work_Orders</fullName>
        <active>true</active>
        <businessProcess>Work Orders</businessProcess>
        <description>Blackout, Deinstallation, Install Brochures, Line Installation, New Installation, Relocation, Repair, Site Survey, Upgrade and Competitor Swap Install</description>
        <label>Work Orders</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CmhId__c</fullName>
        <formula>TEXT(Account__r.CMHID__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cmh Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>Order ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestedDateOfArrival__c</fullName>
        <label>Requested Date of Arrival</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ShippingCity__c</fullName>
        <label>Shipping City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingPostalCode__c</fullName>
        <label>Shipping Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingState__c</fullName>
        <label>Shipping State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingStreet__c</fullName>
        <label>Shipping Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountDetailsControllerTest.cls
@isTest
private class AccountDetailsControllerTest {

	private static Account setup() {
		TestDataService.setupRestEnvironmentProperties();
		TestDataService.setupTestSupplyChainProductAndPackage();
		Map<String, Schema.RecordTypeInfo> accountRecordTypes = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName();
		Map<String, Schema.RecordTypeInfo> caseRecordTypes = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName();

		Contact contact = new Contact();
		contact.FirstName = 'Contact';
		contact.LastName = 'Contact';
		contact.Email = 'contact@email.edu';
		contact.Phone = '1234567890';
		insert contact;

		Account account = new Account();
		account.Name = 'Test Account';
		account.CMHID__c = 12345;
		account.Network__c = 'Network';
		account.BillingPostalCode = '60611';
		account.Primary_Contact__c = contact.Id;
		account.RecordTypeId = accountRecordTypes.get(new Constants.AccountRecordTypes().MEMBER_SERVICES).getRecordTypeId();
		insert account;

		Case workOrder = new Case();
		workOrder.AccountId = account.Id;
		workOrder.RecordTypeId = caseRecordTypes.get(new Constants.CaseRecordTypes().WORK_ORDERS).getRecordTypeId();
		insert workOrder;

		List<Asset> assets = new List<Asset>();
		Asset player = new Asset();
		player.Name = 'Player';
		player.Type__c = 'Player';
		player.AccountId = account.Id;
		assets.add(player);
		Asset unknownPlayer = new Asset();
		unknownPlayer.Name = 'Unknown Player';
		unknownPlayer.Type__c = 'Player';
		unknownPlayer.AccountId = account.Id;
		assets.add(unknownPlayer);
		Asset tablet = new Asset();
		tablet.Name = 'Tablet';
		tablet.Type__c = 'Tablet';
		tablet.AccountId = account.Id;
		assets.add(tablet);
		Asset unknownTablet = new Asset();
		unknownTablet.Name = 'Unknown Tablet';
		unknownTablet.Type__c = 'Tablet';
		unknownTablet.AccountId = account.Id;
		assets.add(unknownTablet);
		insert assets;

		return AccountService.getWithAssetsAndContactsById(account.Id, new List<String> {'BillingCity',
																						 'BillingCountry',
																						 'BillingPostalCode',
																						 'BillingState',
																						 'BIllingStateCode',
																						 'BillingStreet',
																						 'CMHID__c',
																						 'Id',
																						 'Name',
																						 'Network__c',
																						 'Owner.Name',
																						 'Primary_Contact__c',
																						 'RecordType.Name',
																						 'Stage__c',
																						 'Time_Zone__c'}, new List<String> {'ClinicExamRoom__c',
																														    'Id',
																														    'Installation_Status__c',
																														    'InstalledDate__c',
																														    'MountType__c',
																														    'Name',
																														    'Shipment__c',
																														    'Speciality__c',
																														    'Status',
																														    'Type__c',
																														    'Volume__c'}, new List<String> {'Id'});
	}
	
	private static testmethod void testAccountDetailsControllerConstructor() {
		Account account = setup();
		
		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AccountDetailsMock(200));
		AccountDetailsController controller = new AccountDetailsController(new ApexPages.StandardController(account));
		Test.stopTest();

		system.assert(controller.account.Name == 'Test Account');
		system.assert(ListUtils.isNotNullOrEmpty(controller.players));
		system.assert(ListUtils.isNotNullOrEmpty(controller.tablets));
		system.assert(controller.showAssets);
		system.assert(controller.showPlayers);
		system.assert(controller.showShipments);
		system.assert(controller.showTablets);
		system.assert(controller.showWorkOrders);

		system.assert(!controller.showShipmentPackages);
		system.assert(!controller.showShipmentMissingTrackingItems);
		system.assert(!controller.showShipmentHistory);
	}

	private static testmethod void testSaveTablets() {
		Account account = setup();

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AccountDetailsMock(200));
		AccountDetailsController controller = new AccountDetailsController(new ApexPages.StandardController(account));
		controller.saveTablets();
		Test.stopTest();
	}

	private static testmethod void testSaveTablets2() {
		Account account = setup();

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AccountDetailsMock(200));
		AccountDetailsController controller = new AccountDetailsController(new ApexPages.StandardController(account));
		for (Asset tablet : controller.tablets) {
			tablet.Volume__c = 99;
		}
		controller.saveTablets();
		Test.stopTest();
	}

	private static testmethod void testAddProducts() {
		Account account = setup();

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AccountDetailsMock(200));
		AccountDetailsController controller = new AccountDetailsController(new ApexPages.StandardController(account));

		controller.addProducts();
		Test.stopTest();

		system.assert(controller.hasErrors);
	}

	private static testmethod void testAddProducts2() {
		Account account = setup();

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AccountDetailsMock(200));
		AccountDetailsController controller = new AccountDetailsController(new ApexPages.StandardController(account));
		
		controller.selectedProducts = new List<String> {'Product'};
		controller.addProducts();
		Test.stopTest();

		system.assert(controller.showShipmentItems);
	}

	private static testmethod void testAddPackage() {
		Account account = setup();

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AccountDetailsMock(200));
		AccountDetailsController controller = new AccountDetailsController(new ApexPages.StandardController(account));

		controller.addPackage();
		Test.stopTest();

		system.assert(controller.hasErrors);
	}

	private static testmethod void testAddPackage2() {
		Account account = setup();

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AccountDetailsMock(200));
		AccountDetailsController controller = new AccountDetailsController(new ApexPages.StandardController(account));

		controller.selectedPackage = 'Package';
		controller.addPackage();
		Test.stopTest();

		system.assert(controller.showShipmentItems);
	}

	private static testmethod void testRemoveProduct() {
		Account account = setup();

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AccountDetailsMock(200));
		AccountDetailsController controller = new AccountDetailsController(new ApexPages.StandardController(account));
		
		controller.selectedProducts = new List<String> {'Product'};
		controller.addProducts();

		ApexPages.currentPage().getParameters().put('product', 'Product');
		controller.removeProduct();
		Test.stopTest();

		system.assert(controller.shipment.shipmentItems.isEmpty());
	}

	private static testmethod void testCreateShipment() {
		Account account = setup();

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AccountDetailsMock(200));
		AccountDetailsController controller = new AccountDetailsController(new ApexPages.StandardController(account));
		
		controller.shipment.shipment.RequestedDateOfArrival__c = System.today();
		controller.shipment.shipment.ShippingStreet__c = '330 N Wabash';
		controller.shipment.shipment.ShippingCity__c = 'Chicago';
		controller.shipment.shipment.ShippingState__c = 'IL';
		controller.shipment.shipment.ShippingPostalCode__c = '60611';
		controller.selectedPackage = 'Package';
		controller.addPackage();

		Test.setMock(HttpCalloutMock.class, new ShipmentMock(201));
		controller.saveShipment();
		Test.stopTest();
	}

	private static testmethod void testUpdateShipment() {
		Account account = setup();
		Shipment__c shipment = new Shipment__c();
		shipment.Account__c = account.Id;
		shipment.OrderId__c = '12345';
		shipment.RequestedDateOfArrival__c = System.today();
		shipment.ShippingStreet__c = '330 N Wabash';
		shipment.ShippingCity__c = 'Chicago';
		shipment.ShippingState__c = 'IL';
		shipment.ShippingPostalCode__c = '60611';
		insert shipment;

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AccountDetailsMock(200));
		AccountDetailsController controller = new AccountDetailsController(new ApexPages.StandardController(account));
		
		controller.selectedPackage = 'Package';
		controller.addPackage();

		Test.setMock(HttpCalloutMock.class, new ShipmentMock(202));
		ApexPages.currentPage().getParameters().put('orderId', shipment.Id);
		controller.editShipment();
		controller.selectedPackage = 'Package';
		controller.addPackage();
		controller.saveShipment();
		Test.stopTest();
	}

	private static testmethod void testCancelShipment() {
		Account account = setup();
		Shipment__c shipment = new Shipment__c();
		shipment.Account__c = account.Id;
		shipment.OrderId__c = '12345';
		shipment.RequestedDateOfArrival__c = System.today();
		shipment.ShippingStreet__c = '330 N Wabash';
		shipment.ShippingCity__c = 'Chicago';
		shipment.ShippingState__c = 'IL';
		shipment.ShippingPostalCode__c = '60611';
		insert shipment;

		Test.startTest();
		Test.setMock(HttpCalloutMock.class, new AccountDetailsMock(200));
		AccountDetailsController controller = new AccountDetailsController(new ApexPages.StandardController(account));
		
		controller.selectedPackage = 'Package';
		controller.addPackage();

		Test.setMock(HttpCalloutMock.class, new ShipmentMock(200));
		ApexPages.currentPage().getParameters().put('orderId', shipment.Id);
		controller.cancelShipment();
		Test.stopTest();
	}
}