src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DMA_Zip_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>DMA Zip Code</label>
        <referenceTo>Zip_Code_Data__c</referenceTo>
        <relationshipLabel>Accounts (DMA Zip Code)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateofInitialOperation__c</fullName>
        <label>Date of Initial Operation</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Init_touch_Date__c</fullName>
        <label>Touch Point Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Network__c</fullName>
        <description>Used to denote the requested content that a clinic would get if it were to become a member. Formerly known as &quot;Network&quot;.</description>
        <label>Content Requested</label>
        <picklist>
            <picklistValues>
                <fullName>Allergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endocrinology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gastroenterology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infectious Disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neurology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obstetrics and Gynecology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ophthalmology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optometry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rheumatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urology</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Unconfirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unconfirmed_Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed unscheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending IT coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending competitor removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending line drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled - Competitor Removal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial install plays content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial install no content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial install DVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Repair - no content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Repair - playing content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DVD Site - Pending Repair/Awaiting Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uninstalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sold Delayed Confirmation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed Delayed Installation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>offset_st__c</fullName>
        <formula>DMA_Zip_Code__r.OFFSET_ST__c</formula>
        <label>OFFSET ST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>onboarding_specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>OFFSET_ST__c</fullName>
        <formula>Account.DMA_Zip_Code__r.OFFSET_ST__c</formula>
        <label>OFFSET ST</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onboarding_Specialist__c</fullName>
        <formula>Account.onboarding_specialist__r.FirstName + &quot; &quot; +  Account.onboarding_specialist__r.LastName</formula>
        <label>Onboarding Specialist</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Unscheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending IT coordination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending line drop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installed, but IT issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deinstalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled (only for LO)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Zip_Code_Data__c.object
<CustomObject>
    <description>Created by the Cloud Converter from http://ModelMetrics.com</description>
    <fields>
        <fullName>OFFSET_DST__c</fullName>
        <description>UTC Offset Daylight Savings Time</description>
        <inlineHelpText>The Daylights Savings Time offset from UTC</inlineHelpText>
        <label>OFFSET DST</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OFFSET_ST__c</fullName>
        <description>UTC Offset for Standard time</description>
        <inlineHelpText>The Standard Time offset from UTC</inlineHelpText>
        <label>OFFSET ST</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Zip Code Data</label>
    <nameField>
        <label>DMA Zip Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Code Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_AccountTriggerHandler.cls
/*
 * Created By : Lister Technologies
 * Purpose : To Test the account trigger handler.
             

*/
@isTest (SeeAllData=true)
public class Test_AccountTriggerHandler {

        public static testMethod void testMyController1() {
        List<Recordtype> rtypelist=[Select id,name from recordtype where sobjecttype='Account'];
        id memberservice;
        id memberoutreach;
        for(recordtype iterRT : rtypelist){
                 if(iterRT.name=='Member Outreach')
                     memberoutreach=iterRT.id;
                 else if(iterRT.name=='Member Services')
                     memberservice=iterRT.id;    
        }
        ID usrid=UserInfo.getUserId(); 
        Zip_Code_Data__c zcode=new Zip_Code_Data__c(Name='123',OFFSET_DST__c=-1,OFFSET_ST__c=-1,Timezone__c='Eastern');
        insert zcode;
        date myDate = date.newInstance(2014, 6, 1);
        date newDate = mydate.addDays(2);
        Account acc=new Account(Name='Test Account',DMA_Zip_Code__c=zcode.id,recordtypeid=memberoutreach,onboarding_specialist__c=usrid,Stage__c='WaitList',DateofInitialOperation__c=myDate ,Init_touch_Date__c=newDate,Network__c='Diabetes');
        insert acc;
        Event evt=new Event(WhatId=acc.id,subject='Call',EndDateTime=Datetime.parse('12/31/2013 1:00 AM'),StartDateTime=Datetime.parse('12/31/2013 1:00 AM'));
        insert evt;

        /*
        List<RecordType> rtype=new List<RecordType>();
        rtype=[select id from recordtype where name='Member Services' and sobjecttype='Task'];
        if(!rtype.isEmpty()){
        Task tsk=new Task (WhatId=acc.id,subject='Call',status='Completed',priority='Normal',recordtypeid=rtype[0].id);
        insert tsk;
        }
        zcode.Timezone__c='Western';
        update zcode;
        */
        acc.name='Test Account Modified';
        acc.recordtypeid=memberservice;
        
        update acc;
        }
        
        
        
        public static testMethod void testMyController2() {
        List<Recordtype> rtypelist=[Select id,name from recordtype where sobjecttype='Account'];
        id memberservice;
        id memberoutreach;
        for(recordtype iterRT : rtypelist){
                 if(iterRT.name=='Member Outreach')
                     memberoutreach=iterRT.id;
                 else if(iterRT.name=='Member Services')
                     memberservice=iterRT.id;    
        }
        ID usrid=UserInfo.getUserId(); 
        Zip_Code_Data__c zcode=new Zip_Code_Data__c(Name='xyztest',OFFSET_DST__c=-1,OFFSET_ST__c=-1,Timezone__c='Eastern');
        insert zcode;
        date myDate = date.newInstance(2014, 6, 1);
        date newDate = mydate.addDays(2);
        Account acc=new Account(Name='Test CMH ID Account',DMA_Zip_Code__c=zcode.id,recordtypeid=memberoutreach,onboarding_specialist__c=usrid,Stage__c='WaitList',DateofInitialOperation__c=myDate ,Network__c='Rheumatoid'  );
        insert acc;
        acc.recordtypeid=memberservice;
        
        update acc;
        List <Case> cselist=[select id from case where accountid=:acc.id ];
        delete cselist;
        
        delete acc;
          
        
        }
        public static testMethod void testMyController3() {
        List<Recordtype> rtypelist=[Select id,name from recordtype where sobjecttype='Account'];
        id memberservice;
        id memberoutreach;
        for(recordtype iterRT : rtypelist){
                 if(iterRT.name=='Member Outreach')
                     memberoutreach=iterRT.id;
                 else if(iterRT.name=='Member Services')
                     memberservice=iterRT.id;    
        }
        ID usrid=UserInfo.getUserId(); 
        Zip_Code_Data__c zcode=new Zip_Code_Data__c(Name='xyztest',OFFSET_DST__c=-1,OFFSET_ST__c=-1,Timezone__c='Eastern');
        insert zcode;
        date myDate = date.newInstance(2014, 6, 1);
        date newDate = mydate.addDays(2);
        Account acc=new Account(Name='Test CMH ID Account',DMA_Zip_Code__c=zcode.id,recordtypeid=memberoutreach,onboarding_specialist__c=usrid,Stage__c='WaitList',DateofInitialOperation__c=myDate ,Network__c='GI'  );
        insert acc;
        acc.recordtypeid=memberservice;
        
        update acc;
        List <Case> cselist=[select id from case where accountid=:acc.id ];
        delete cselist;
        
        delete acc;
          
        
        }
        
        public static testMethod void testMyController4() {
        List<Recordtype> rtypelist=[Select id,name from recordtype where sobjecttype='Account'];
        id memberservice;
        id memberoutreach;
        for(recordtype iterRT : rtypelist){
                 if(iterRT.name=='Member Outreach')
                     memberoutreach=iterRT.id;
                 else if(iterRT.name=='Member Services')
                     memberservice=iterRT.id;    
        }
        ID usrid=UserInfo.getUserId(); 
        Zip_Code_Data__c zcode=new Zip_Code_Data__c(Name='xyztest',OFFSET_DST__c=-1,OFFSET_ST__c=-1,Timezone__c='Eastern');
        insert zcode;
        date myDate = date.newInstance(2014, 6, 1);
        date newDate = mydate.addDays(2);
        Account acc=new Account(Name='Test CMH ID Account',DMA_Zip_Code__c=zcode.id,recordtypeid=memberoutreach,onboarding_specialist__c=usrid,Stage__c='WaitList',DateofInitialOperation__c=myDate ,Network__c='Diabetes'  );
        insert acc;
        acc.recordtypeid=memberservice;
        
        update acc;
        List <Case> cselist=[select id from case where accountid=:acc.id ];
        delete cselist;
        
        delete acc;
          
        
        }
        public static testMethod void testMyController5() {
        List<Recordtype> rtypelist=[Select id,name from recordtype where sobjecttype='Account'];
        id memberservice;
        id memberoutreach;
        for(recordtype iterRT : rtypelist){
                 if(iterRT.name=='Member Outreach')
                     memberoutreach=iterRT.id;
                 else if(iterRT.name=='Member Services')
                     memberservice=iterRT.id;    
        }
        ID usrid=UserInfo.getUserId(); 
        Zip_Code_Data__c zcode=new Zip_Code_Data__c(Name='xyztest',OFFSET_DST__c=-1,OFFSET_ST__c=-1,Timezone__c='Eastern');
        insert zcode;
        date myDate = date.newInstance(2014, 6, 1);
        date newDate = mydate.addDays(2);
        Account acc=new Account(Name='Test CMH ID Account',DMA_Zip_Code__c=zcode.id,recordtypeid=memberoutreach,onboarding_specialist__c=usrid,Stage__c='WaitList',DateofInitialOperation__c=myDate ,Network__c='Neurology'  );
        insert acc;
        acc.recordtypeid=memberservice;
        
        update acc;
        List <Case> cselist=[select id from case where accountid=:acc.id ];
        delete cselist;
        
        delete acc;
          
        
        }
       
       
       public static testMethod void testMyController6() {
        

        User silivia=[select name,id,email from user where name='Silvia Velazquez'];
        User nonsilivia=[select name,id,email from user where name<>'Silvia Velazquez' and IsActive=true limit 1];
        Account acc=new Account(Name='Test Account',Stage__c='WaitList',Network__c='Diabetes',ownerid=nonsilivia.id);
        insert acc;
        
        acc.name='Test Account Modified';
        acc.ownerid=silivia.id;
        update acc;
        acc.ownerid=nonsilivia.id;
        update acc;
        }
       
}