src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Clinic_Office_Hours__c</fullName>
        <label>Clinic Office Hours</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CompetitorRemovalNotes__c</fullName>
        <label>Competitor Removal Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IdGenerator__c</fullName>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Network__c</fullName>
        <description>Used to denote the requested content that a clinic would get if it were to become a member. Formerly known as &quot;Network&quot;.</description>
        <label>Content Requested</label>
        <picklist>
            <picklistValues>
                <fullName>Allergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endocrinology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gastroenterology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infectious Disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neurology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obstetrics and Gynecology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ophthalmology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optometry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rheumatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urology</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>NumberOfExamRooms__c</fullName>
        <label># of Exam Rooms</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OfficeType__c</fullName>
        <label>Office Type</label>
        <picklist>
            <picklistValues>
                <fullName>Private Practice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>University-based</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hospital-based</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OpenCaptioning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Open Captioning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SignUpFormCompleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sign-Up Form Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Under17__c</fullName>
        <description>% of patients that are under 17</description>
        <label>Under 17</label>
        <picklist>
            <picklistValues>
                <fullName>0%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-20%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21-50%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51-75%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>76-100%</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>of_Waiting_Rooms__c</fullName>
        <label># of Waiting Rooms</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>BAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV &amp; PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV &amp; PC &amp; Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard 32 Touch Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard 40 Touch Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WR WiFi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WR WiFi - Sprint</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RequestedInstallDates__c</fullName>
        <label>Requested Install Dates</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Cable Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Deinstall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Outlet Locks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Line Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Device Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Deinstall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Player Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tech Only Dispatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Troubleshooting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV &amp; Tablet Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard Swap</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Prescriber__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Prescriber</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specialty__c</fullName>
        <label>Specialty</label>
        <picklist>
            <picklistValues>
                <fullName>Adolescent Medicine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Medicine/Pediatrics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambulatory Medicine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anesthesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APRN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audiologist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bariatrics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bariatric Surgeon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Operating Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Psychiatry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiropractic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRNP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dentistry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diabetology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dietician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Medicine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endocrinology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Epidemiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Practice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gastroenterology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Surgery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geriatric Psychiatry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geriatrics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <picklist>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accountant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admissions Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aesthetician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Area Practice Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARNP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant IT Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Office Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Maintanence Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Dental Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Medical Officer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SlingshotController.cls
public with sharing class SlingshotController {
	public SlingshotController() {}

	@RemoteAction
	public static Map<String, Object> getOptions(String referenceNumber) {
		Map<String, Schema.SObjectField> accountFields = Schema.SObjectType.Account.fields.getMap();
		Map<String, Object> result = new Map<String, Object>();

		List<String> clinicSpecialties = new List<String> {};
		for (Schema.PicklistEntry entry : Schema.Account.Network__c.getDescribe().getPicklistValues()) {
			clinicSpecialties.add(entry.getLabel());
		}
		List<String> demographicOptions = new List<String>();
		for (Schema.PicklistEntry entry : Schema.Account.Under17__c.getDescribe().getPicklistValues()) {
			demographicOptions.add(entry.getLabel());
		}
		List<String> facilityTypes = new List<String>();
		for (Schema.PicklistEntry entry : Schema.Account.OfficeType__c.getDescribe().getPicklistValues()) {
			facilityTypes.add(entry.getLabel());
		}
		List<String> providerSpecialties = new List<String>();
		for (Schema.PicklistEntry entry : Schema.Contact.Specialty__c.getDescribe().getPicklistValues()) {
			providerSpecialties.add(entry.getLabel());
		}
		List<String> titles = new List<String>();
		for (Schema.PicklistEntry entry : Schema.Contact.Title__c.getDescribe().getPicklistValues()) {
			titles.add(entry.getLabel());
		}

		Account account;
		if (referenceNumber == null || referenceNumber == '') {
			account = new Account();
		}
		else {
			account = [Select Name, (Select FirstName, LastName, Specialty__c, Title__c From Contacts Where Prescriber__c = true) From Account Where IdGenerator__c =: referenceNumber];
		}
		List<Account> clinics = new List<Account>();
		List<String> clinicFields = new List<String> {'COID__c',
													  'eCW__c',
													  'CompetitorRemoval__c',
													  'CompetitorRemovalNotes__c',
													  'BillingStreet',
													  'BillingState',
													  'BillingCity',
													  'BillingPostalCode',
													  'Clinic_Office_Hours__c',
													  'of_Waiting_Rooms__c',
													  'NumberOfExamRooms__c',
													  'SharedWaitingRoom__c',
													  'SignUpFormCompleted__c',
													  'SpecialContentRequest__c',
													  'Name',
													  'Parent.Name'};

		List<Account> children = AccountService.getWithPrescribersByParentIdsWithOrder(new List<Id> {account.Id}, clinicFields, new List<String> {'FirstName', 'LastName', 'Specialty__c', 'Title__c'}, 'Name');
		while (ListUtils.isNotNullOrEmpty(children)) {
			clinics.addAll(children);

			List<Id> childIds = new List<Id>();
			for (Account child : children) {
				childIds.add(child.Id);
			}
			children = AccountService.getWithPrescribersByParentIdsWithOrder(childIds, clinicFields, new List<String> {'FirstName', 'LastName', 'Specialty__c', 'Title__c'}, 'Name');
		}

		result.put('clinics', clinics);
		result.put('clinicSpecialties', clinicSpecialties);
		result.put('demographics', demographicOptions);
		result.put('facilityTypes', facilityTypes);
		result.put('providerSpecialties', providerSpecialties);
		result.put('quantities', new List<Integer> {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10});
		result.put('schedulableDays', new List<String> {'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'});
		result.put('states', new List<String> {'Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','District Of Columbia','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming'});
		result.put('titles', titles);
		result.put('waitTimes', new List<String> {'1-10 Minutes', '11-20 Minutes', '21-30 Minutes', '>30 Minutes'});

		return result;
	}

	@RemoteAction
	public static void save(Account account, Contact contact, Case itapproval, Case workorder, List<Contact> providers, Map<String, Boolean> specialties, Map<String, String> scheduledDays) {
		Map<String, Schema.RecordTypeInfo> caseRecordTypes = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName();
		contact.AccountId = account.Id;

		itapproval.AccountId = account.Id;
		itapproval.RecordTypeId = caseRecordTypes.get('IT Approval').getRecordTypeId();
		itapproval.Subject = 'IT Approval';

		workorder.AccountId = account.Id;
		workorder.Product__c = 'TV & PC & Tablet';
		workorder.RecordTypeId = caseRecordTypes.get('Work Orders').getRecordTypeId();
		workorder.Service__c = 'Installation';
		workorder.Subject = '*HCA Installation*';
		workorder.Type = 'New Installation';

		if (scheduledDays != null) {
			String finalScheduledDays = '';
			for (String day : scheduledDays.keySet()) {
				finalScheduledDays += day + ': ' + scheduledDays.get(day) + '\n';
			}
			workorder.RequestedInstallDates__c = finalScheduledDays;
		}
		for (Contact provider : providers) {
			provider.AccountId = account.Id;
		}
		List<String> content = new List<String>();
		for (String specialty : specialties.keySet()) {
			if (specialties.get(specialty)) {
				content.add(specialty);
			}
		}
		if (ListUtils.isNotNullOrEmpty(content)) {
			account.Network__c = String.join(content, ';');
		}

		account.BillingCountryCode = 'US';
		account.SignUpFormCompleted__c = true;
		account.OpenCaptioning__c = true;
		account.Brochure_Shipment_Opt_Out__c = true;
		account.Stage__c = 'Confirmed Unscheduled';

		try {
			update account;

			providers.add(contact);
			upsert providers;

			List<Case> casesToInsert = new List<Case> {itapproval, workorder};
			insert casesToInsert;
		}
		catch(Exception ex) {
			system.debug('caught the exception...');
			system.debug(ex);
			throw ex;
		}
	}
}