src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CMHID__c</fullName>
        <externalId>true</externalId>
        <label>CMH ID</label>
        <precision>17</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NetworkDeploymentSpecialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Network Deployment Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>AccessToNetwork__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Access to Network</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Best_Day_Time_etc_for_Install__c</fullName>
        <label>Best Day/Time/etc for Install WR</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Connectivity_Method_New__c</fullName>
        <label>Connectivity Method</label>
        <picklist>
            <picklistValues>
                <fullName>LAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sprint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verizon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wifi</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Daily_WiFi_Authentication_Required__c</fullName>
        <label>Daily WiFi Authentication Required?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Data_Drop_Access__c</fullName>
        <label>Data Drop Access (WR)</label>
        <picklist>
            <picklistValues>
                <fullName>Drop Tile Ceiling Throughout Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No availability</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Electrical_Outlet_near_requested_TV_loca__c</fullName>
        <label>Electrical Outlet near requested TV loc?</label>
        <picklist>
            <picklistValues>
                <fullName>&lt;5 feet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6-10 feet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;10 feet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not all TVs have an outlet nearby</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional TVs are all within parameters</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ethernet_outlet_near_requested_TV_loc__c</fullName>
        <inlineHelpText>In Feet</inlineHelpText>
        <label>Dist from WR to internet jack or router</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IT_Contact_Name__c</fullName>
        <label>IT Contact Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Email_Address__c</fullName>
        <label>IT Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IT_Phone_Number__c</fullName>
        <label>IT Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>If_No_distance_to_ethernet_outlet__c</fullName>
        <label>If No, distance to ethernet outlet?</label>
        <picklist>
            <picklistValues>
                <fullName>Less than 10ft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than 10 ft but less than 25 ft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than 25 ft but less than 100ft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than 100 ft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dont Know</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>If_no_will_traffic_through_a_proxy_serv__c</fullName>
        <label>Is outbound traffic blocked?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>If_ports_not_accessible_can_ports_be_o__c</fullName>
        <label>Can IT open required ports if blocked?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_WiFi_Available__c</fullName>
        <label>Is WiFi Available?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_office_network_DHCP__c</fullName>
        <label>Is office network DHCP?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dont Know</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MPTypeofInternet__c</fullName>
        <label>Brand of Internet</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberofTVRemovedRelocated__c</fullName>
        <description>Number of TVs being removed/relocated</description>
        <label>Number of TVs being Removed/Relocated</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ports_10799_10805_21_80_443_access__c</fullName>
        <label>Ports 10799, 10805, 21, 80, 443 access?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dont Know</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recommended_Player_Type__c</fullName>
        <label>Recommended Player Type</label>
        <picklist>
            <picklistValues>
                <fullName>LAN Connected (standard player)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WiFi Player</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sprint/Verizon Player</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ScopeofWorkNotes__c</fullName>
        <label>Scope of Work Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TabletConnectionType__c</fullName>
        <label>Tablet Connection Type (IT)</label>
        <picklist>
            <picklistValues>
                <fullName>Clinic&apos;s Network</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Verizon</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>WIFISpecialCharacters__c</fullName>
        <label>WIFI Special Characters</label>
        <picklist>
            <picklistValues>
                <fullName>Yes, send Almond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Work_Orders</fullName>
        <active>true</active>
        <businessProcess>Work Orders</businessProcess>
        <description>Blackout, Deinstallation, Install Brochures, Line Installation, New Installation, Relocation, Repair, Site Survey, Upgrade and Competitor Swap Install</description>
        <label>Work Orders</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Date__c.object
<CustomObject>
    <description>Service Dates for Work Orders</description>
    <fields>
        <fullName>Related_Work_Order__c</fullName>
        <label>Related Work Order</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Dates</relationshipLabel>
        <relationshipName>Service_Dates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceDateEnd__c</fullName>
        <label>Service Date - End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ServiceDateStart__c</fullName>
        <label>Service Date - Start</label>
        <type>DateTime</type>
    </fields>
    <label>Service Date</label>
    <nameField>
        <displayFormat>ServiceDate-{000000}</displayFormat>
        <label>Service Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InstallationApprovalController.cls
public with sharing class InstallationApprovalController {
	public Case installationApproval {get;set;}

	public Account account {get;set;}
	public Case workOrder {get;set;}
	public Service_Date__c serviceDate {get;set;}

	public List<String> connectivityMethods {get;set;}
	public String specialInstructions {get;set;}

	public InstallationApprovalController(ApexPages.StandardController standardController) { 
		installationApproval = (Case)standardController.getRecord();
		installationApproval = CaseService.getById(installationApproval.Id, new List<String> { 'Account.Name',
																							   'Account.NetworkDeploymentSpecialist__r.FirstName',
																							   'Account.NetworkDeploymentSpecialist__r.LastName',
																							   'Account.NetworkDeploymentSpecialist__r.Phone',
																							   'AccessToNetwork__c',
																							   'Best_Day_Time_etc_for_Install__c',
																							   'Connectivity_Method_New__c',
																							   'Daily_WiFi_Authentication_Required__c',
																							   'Data_Drop_Access__c',
																							   'Electrical_Outlet_near_requested_TV_loca__c',
																							   'Ethernet_outlet_near_requested_TV_loc__c',
																							   'Id',
																							   'If_No_distance_to_ethernet_outlet__c',
																							   'If_no_will_traffic_through_a_proxy_serv__c',
																							   'If_ports_not_accessible_can_ports_be_o__c',
																							   'Is_office_network_DHCP__c',
																							   'Is_WiFi_Available__c',
																							   'IT_Contact_Name__c',
																							   'IT_Email_Address__c',
																							   'IT_Phone_Number__c',
																							   'MPTypeofInternet__c',
																							   'NumberofTVRemovedRelocated__c',
																							   'Ports_10799_10805_21_80_443_access__c',
																							   'Recommended_Player_Type__c',
																							   'Status',
																							   'Subject',
																							   'TabletConnectionType__c',
																							   'WIFISpecialCharacters__c'
																							   });
		account = AccountService.getById(installationApproval.AccountId, new List<String> { 'CMHID__c',
																							'Id',
																							'Name'});
		workOrder = new Case();
		workOrder.RecordTypeId = RecordTypeService.getByNameAndObjectType(new Constants.CaseRecordTypes().WORK_ORDERS, 'Case', new List<String> {'Id'}).Id;
		workOrder.Type = new Constants.CaseTypes().NEW_INSTALLATION;
		workOrder.AccountId = account.Id;
		workOrder.ParentId = installationApproval.Id;
		workOrder.OwnerId = UserInfo.getUserId();

		serviceDate = new Service_Date__c();

		connectivityMethods = new List<String>();
		if (installationApproval.Connectivity_Method_New__c != null && installationApproval.Connectivity_Method_New__c != '') {
			connectivityMethods.addAll(installationApproval.Connectivity_Method_New__c.split(';'));
		}
		if (installationApproval.Status == new Constants.CaseStatuses().CLOSED) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, new Constants.InfoMessages().INSTALLATION_INFO_CLOSED));
		}
	}

	public PageReference submit() {
		if (installationApproval.Status == new Constants.CaseStatuses().CLOSED) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, new Constants.ExceptionMessages().INSTALLATION_EXCEPTION_CLOSED));
			return null;
		}
		if (ListUtils.isNullOrEmpty(connectivityMethods)) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, new Constants.ExceptionMessages().INSTALLATION_EXCEPTION_CONNECTIVITY_METHOD));
			return null;
		}
		if (isMissingRequiredFields(installationApproval)) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, new Constants.ExceptionMessages().INSTALLATION_EXCEPTION_REQUIRED_FIELDS));
			return null;
		}

		SavePoint savePoint = Database.setSavePoint();
		try {
			workOrder.Subject = workOrder.Type + ' @ ' + String.valueOf(serviceDate.ServiceDateStart__c.format('MM/dd/yyyy hh:mm a'));
			workOrder.ScopeofWorkNotes__c = CaseService.getScopeOfWork(String.valueOf(account.CMHID__c),
																	   workOrder,
																	   installationApproval,
																	   specialInstructions);
			upsert workOrder;

			serviceDate.Related_Work_Order__c = workOrder.Id;
			if (serviceDate.ServiceDateEnd__c == null) {
				serviceDate.ServiceDateEnd__c = serviceDate.ServiceDateStart__c;
			}
			upsert serviceDate;

			String connectivity = '';
			for (String method : connectivityMethods) {
				if (connectivity == '') {
					connectivity = method;
				}
				else {
					connectivity += ';' + method;
				}
			}
			installationApproval.Connectivity_Method_New__c = connectivity;
			installationApproval.Status = new Constants.CaseStatuses().CLOSED;
			update installationApproval;

			PageReference workOrderPage = Page.CaseDetails;
			workOrderPage.getParameters().put('id', workOrder.Id);
			return workOrderPage;
		}
		catch(Exception ex) {
			Database.rollback(savePoint);
			workOrder.Id = null;
			serviceDate.Id = null;
			serviceDate.Related_Work_Order__c = null;
			EmailUtils.sendHTMLEmail(new List<String> { 'matt.t@contextmediainc.com' }, new Constants.ExceptionMessages().INSTALLATION_EXCEPTION_SAVE, ex.getMessage() + '<br/><br/>' + ex.getStackTraceString());
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()));
		}
		return null;
	}

	private Boolean isMissingRequiredFields(Case installationApproval) {
		if (installationApproval.AccessToNetwork__c && 
			(installationApproval.Is_office_network_DHCP__c == null
			|| installationApproval.Electrical_Outlet_near_requested_TV_loca__c == null
			|| installationApproval.Data_Drop_Access__c == null
			|| installationApproval.NumberofTVRemovedRelocated__c == null
			|| installationApproval.Is_WiFi_Available__c == null
			|| installationApproval.Daily_WiFi_Authentication_Required__c == null)) {
			return true;
		}
		else {
			return false;
		}
	}

}