src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>RelatedWorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Work Order</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Player</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Sprint Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cradle Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Verizon Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verizon USB Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wifi Hotspot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <formula>Account.Primary_Contact__r.FirstName &amp; &apos; &apos; &amp; Account.Primary_Contact__r.LastName</formula>
        <label>Primary Contact</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>BAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV &amp; PC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV &amp; PC &amp; Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard 32 Touch Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard 40 Touch Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WR WiFi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WR WiFi - Sprint</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Pricebook2.object
<CustomObject>
    <fields>
        <fullName>PackageCode__c</fullName>
        <label>Package Code</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/PricebookEntry.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Box__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Box</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hidden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Hidden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Type1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <label>Company</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Account__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExpediteReason__c</fullName>
        <label>Expedite Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Avoid Significant Install Delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prevent Deinstall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quick Revisit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduling Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RelatedWorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Work Order</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShippingCity__c</fullName>
        <label>Shipping City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingPostalCode__c</fullName>
        <label>Shipping Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingState__c</fullName>
        <label>Shipping State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingStreet2__c</fullName>
        <label>Shipping Street 2</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingStreet__c</fullName>
        <label>Shipping Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShipmentItem__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Shipment Items</relationshipLabel>
        <relationshipName>ShipmentItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Items</relationshipLabel>
        <relationshipName>Shipment_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Shipment Item</label>
    <nameField>
        <label>Shipment Item SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ShipmentPackage__c.object
<CustomObject>
    <fields>
        <fullName>ProductCode__c</fullName>
        <description>This field will contain the list of SKU numbers in the package in JASON format.</description>
        <label>ProductCode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>ShipmentPackages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Shipment Package</label>
    <nameField>
        <label>ShipmentPackage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Shipment.cls
public with sharing class Shipment {
	
	public Shipment__c shipment {get;set;}
	public Map<String, LineItem> shipmentItems {get;set;}
	public List<LineItem> shipmentItemsList { get { return shipmentItems.values(); } }
	public List<ReturnItem> returnItems {get;set;}

	public Map<String, Product2> products {get;set;}
	public List<SelectOption> productOptions {get;set;}
	public Map<String, Pricebook2> packages {get;set;}
	public List<SelectOption> packageOptions {get;set;}
	public List<SelectOption> expediteReasons {
		get {
			List<SelectOption> result = new List<SelectOption> { new SelectOption('', '--') };
			for (Schema.PicklistEntry entry : Schema.Shipment__c.ExpediteReason__c.getDescribe().getPicklistValues()) {
				result.add(new SelectOption(entry.getValue(), entry.getLabel()));
			}
			return result;
		}
	}
    
    public Map<id, List<LineItem>>  shipmentPackages {get;set;}

	public Shipment(Account account){ this(account, null); }
	public Shipment(Account account, Case thisCase) {
		clear(account, thisCase);
		
		List<Pricebook2> packageList = ShipmentService.getCustomPricebooksWithPricebookEntries(new List<String> {'Name',
																												 'PackageCode__c'},
																							   new List<String> {'Product2Id',
																							   					 'ProductCode',
																												 'Quantity__c'});
		packages = new Map<String, Pricebook2>();
		packageOptions = new List<SelectOption>();
		for (Pricebook2 thePackage : packageList) {
			packages.put(thePackage.PackageCode__c, thePackage);
			packageOptions.add(new SelectOption(thePackage.PackageCode__c, thePackage.Name));
		}
		List<Product2> productList = ShipmentService.getActiveProducts(new List<String> {'Box__c',
																						 'Box__r.ProductCode',
																						 'Family',
																						 'Hidden__c',
																						 'Id',
																						 'Name',
																						 'ProductCode'});
		products = new Map<String, Product2>();
		productOptions = new List<SelectOption>();
		for (Product2 product : productList) {
			if (product.Hidden__c) {
				if (PermissionUtils.hasPermissionSet('ProductAdministrator', UserInfo.getUserId())) {
					products.put(product.ProductCode, product);
					productOptions.add(new SelectOption(product.ProductCode, product.ProductCode + ' - ' + product.Name));
				}
			}
			else {
				products.put(product.ProductCode, product);
				productOptions.add(new SelectOption(product.ProductCode, product.ProductCode + ' - ' + product.Name));
			}
		}
		if (ListUtils.isNotNullOrEmpty(account.Assets)) {
			returnItems = new List<ReturnItem>();
			for (Asset asset : account.Assets) {
				if (asset.Status == 'Installed' || asset.Status == 'Shipped') {
					ReturnItem returnItem = new ReturnItem();
					returnItem.asset = asset;
					returnItem.returning = asset.Shipment__c != null;
					returnItems.add(returnItem);
				}
			}
		}
	}

	public void load(Shipment__c shipmentToLoad, List<Asset> assets) {
		shipment = shipmentToLoad;
		shipmentItems = new Map<String, LineItem>();
		for (ShipmentItem__c shipmentItem : shipmentToLoad.Shipment_Items__r) {
			LineItem lineItem = new LineItem();
			lineItem.productId = shipmentItem.Product__c;
			lineItem.productCode = shipmentItem.Product__r.ProductCode;
			lineItem.productName = shipmentItem.Product__r.Name;
			lineItem.quantity = Integer.valueOf(shipmentItem.Quantity__c);
			lineItem.type = shipmentItem.Type__c;
			shipmentItems.put(lineItem.productCode, lineItem);
		}

		shipmentPackages = new map<id,List<LineItem>>();
		for (ShipmentPackage__c shipPackage : shipment.ShipmentPackages__r) {
			List<String> productCodes = shipPackage.ProductCode__c.split(',');
			 
			List<LineItem> packageContents = new List<LineItem>();
			for (String code : productCodes) {
				packageContents.add(shipmentItems.get(code));
			}
			shipmentPackages.put(shipPackage.Id, packageContents);
		}

		for (ShipmentPackage__c shipPackage : shipment.ShipmentPackages__r) {
			List<String> productCodes = shipPackage.ProductCode__c.split(',');
			for (String code : productCodes) {
				shipmentItems.remove(code);
			}
		}

		if (ListUtils.isNotNullOrEmpty(assets)) {
			refreshReturnItems(assets);
		}
	}

	public void refreshReturnItems(List<Asset> assets) {
		if (ListUtils.isNotNullOrEmpty(assets)) {
			returnItems = new List<ReturnItem>();
			for (Asset asset : assets) {
				if (asset.Status == 'Installed') {
					ReturnItem returnItem = new ReturnItem();
					returnItem.asset = asset;
					returnItem.returning = asset.Shipment__c != null;
					returnItems.add(returnItem);
				}
			}
		}
	}

	public void clear(Account account, Case thisCase) {
		shipment = new Shipment__c();
		shipmentItems = new Map<String, LineItem>();

		shipment.Account__c = account.Id;
		shipment.Company__c = account.Name;
		shipment.Contact__c = thisCase == null ? account.Primary_Contact__c : thisCase.ContactId;
		if (shipment.ShippingStreet__c == null) {
			if (account.BillingStreet != null) {
				List<String> streetAddress = account.BillingStreet.split('\n');
				shipment.ShippingStreet__c = streetAddress[0];
				if (streetAddress.size() > 1) {
					shipment.ShippingStreet2__c = streetAddress[1];
				}
			}
			shipment.ShippingCity__c = account.BillingCity;
			shipment.ShippingState__c = account.BillingStateCode;
			shipment.ShippingPostalCode__c = account.BillingPostalCode;
		}
		if (thisCase != null) {
			shipment.RelatedWorkOrder__c = thisCase.Id;
		}
		if (ListUtils.isNotNullOrEmpty(returnItems)) {
			for (ReturnItem returnItem : returnItems) {
				if (returnItem.asset.Shipment__c == null) {
					returnItem.returning = false;
				}
			}
		}
	}

	public List<String> addPackage(String packageCode) {
		List<String> existingProducts = new List<String>();
		Pricebook2 thePackage = packages.get(packageCode);
		for (PricebookEntry entry : thePackage.PriceBookEntries) {
			if (shipmentItems.get(entry.ProductCode) == null) {
				LineItem lineItem = new LineItem();
				lineItem.productId = products.get(entry.ProductCode).Id;
				lineItem.productName = products.get(entry.ProductCode).Name;
				lineItem.productCode = entry.ProductCode;
				lineItem.quantity = Integer.valueOf(entry.Quantity__c == null ? 1 : entry.Quantity__c);
				shipmentItems.put(entry.ProductCode, lineItem);
			}
			else {
				shipmentItems.get(entry.ProductCode).quantity += Integer.valueOf(entry.Quantity__c);
				existingProducts.add(entry.ProductCode);
			}
		}
		return existingProducts;
	}

	public List<String> addProducts(List<String> productCodes) {
		List<String> existingProducts = new List<String>();
		if (ListUtils.isNotNullOrEmpty(productCodes)) {
			for (String productCode : productCodes) {
				if (productCode != null && shipmentItems.get(productCode) == null) {
					LineItem lineItem = new LineItem();
					lineItem.productId = products.get(productCode).Id;
					lineItem.productName = products.get(productCode).Name;
					lineItem.productCode = productCode;
					lineItem.type = products.get(productCode).Family;
					lineItem.quantity = 1;
					shipmentItems.put(productCode, lineItem);
				}
				else {
					shipmentItems.get(productCode).quantity++;
					existingProducts.add(productCode);
				}
			}
		}
		return existingProducts;
	}

	public void remove(String productCode) {
		shipmentItems.remove(productCode);
	}

	public class LineItem {
		public Id productId {get;set;}
		public String productCode {get;set;}
		public String productName {get;set;}
		public String type {get;set;}
		public Integer quantity {get;set;}
	}

	public class ReturnItem {
		public Boolean returning {get;set;}
		public Asset asset {get;set;}
	}
}