src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Under17__c</fullName>
        <description>% of patients that are under 17</description>
        <label>Under 17</label>
        <picklist>
            <picklistValues>
                <fullName>0%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-20%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21-50%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>51-75%</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>76-100%</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Specialty__c</fullName>
        <label>Specialty</label>
        <picklist>
            <picklistValues>
                <fullName>Adolescent Medicine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Medicine/Pediatrics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambulatory Medicine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anesthesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APRN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audiologist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bariatrics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bariatric Surgeon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Operating Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Psychiatry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiropractic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRNP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dentistry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diabetology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dietician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Medicine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endocrinology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Epidemiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Practice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gastroenterology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Surgery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geriatric Psychiatry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geriatrics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <picklist>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accountant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admissions Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aesthetician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Area Practice Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARNP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant IT Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Office Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Maintanence Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Dental Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Medical Officer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PatientDemographics__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>FieldNames__c</fullName>
        <label>Field Names</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Patient Demographics</label>
</CustomObject>

src/classes/SignupTest.cls
@isTest
private class SignupTest {

	private static testmethod void testSignup() {
		SignupController controller = new SignupController();
		String terms = controller.wifiTermsAndConditions;
	}

	private static testmethod void testSignup2() {
		PatientDemographics__c demographics = new PatientDemographics__c(Name = 'All', FieldNames__c = 'Under17__c');
		insert demographics;
		Map<String, Object> options = SignupController.getOptions();
	}

	private static testmethod void testSignup3() {
		SignupController.save(new Account(Name = 'WHATEVER'), new Contact(FirstName = 'Name', LastName = 'Name', Title__c = 'Title', Specialty__c = 'Specialty'), new List<SignupController.Provider>{});
	}
}