src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NetworkDeploymentSpecialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Network Deployment Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts5</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Player</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Sprint Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cradle Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Verizon Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verizon USB Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wifi Hotspot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Best_Day_Time_etc_for_Install__c</fullName>
        <label>Best Day/Time/etc for Install WR</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IT_Contact_Name__c</fullName>
        <label>IT Contact Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Email_Address__c</fullName>
        <label>IT Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IT_Phone_Number__c</fullName>
        <label>IT Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Players_Being_Installed__c</fullName>
        <label># Players Being Installed</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recommended_Player_Type__c</fullName>
        <label>Recommended Player Type</label>
        <picklist>
            <picklistValues>
                <fullName>LAN Connected (standard player)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WiFi Player</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sprint/Verizon Player</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Routers_Being_Installed__c</fullName>
        <label>Routers Being Installed</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>Cable Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitor Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Deinstall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Install Outlet Locks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Line Install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Device Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial Deinstall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Player Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Relocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tech Only Dispatch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Troubleshooting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV &amp; Tablet Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TV Swap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wallboard Swap</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TVs_Being_Installed__c</fullName>
        <label># TVs Being Installed</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TabletConnectionType__c</fullName>
        <label>Tablet Connection Type (IT)</label>
        <picklist>
            <picklistValues>
                <fullName>Clinic&apos;s Network</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Verizon</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tablets_Being_Installed__c</fullName>
        <label># Tablets Being Installed</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Cases</fullName>
        <active>true</active>
        <businessProcess>Cases and Changes</businessProcess>
        <description>Account Management, Affiliate Office Sale, Content Request, Deinstallation, IT Approval, Missing Equipment, Other, Player MIA in BS, Potential Upgrade, Reported Issue, Shipping Issue and New Sale Cases.</description>
        <label>Cases</label>
    </recordTypes>
    <recordTypes>
        <fullName>Work_Orders</fullName>
        <active>true</active>
        <businessProcess>Work Orders</businessProcess>
        <description>Blackout, Deinstallation, Install Brochures, Line Installation, New Installation, Relocation, Repair, Site Survey, Upgrade and Competitor Swap Install</description>
        <label>Work Orders</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Date__c.object
<CustomObject>
    <description>Service Dates for Work Orders</description>
    <fields>
        <fullName>Related_Work_Order__c</fullName>
        <label>Related Work Order</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Dates</relationshipLabel>
        <relationshipName>Service_Dates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service Date</label>
    <nameField>
        <displayFormat>ServiceDate-{000000}</displayFormat>
        <label>Service Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedWorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Work Order</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseService.cls
public class CaseService {
	private static final String CASEx = 'Case';
	private static final String SERVICEDATESx = 'Service_Dates__r';
	private static final String SHIPMENTSx = 'Shipments__r';
	
	public static Case getById(Id caseId, List<String> fields) {
		String soql = new SoqlBuilder()
						  .selectx(fields)
						  .fromx(CASEx)
						  .wherex(new FieldCondition('Id').equals(caseId))
						  .toSoql();
		return Database.query(soql);
	}

	public static List<Case> getByIds(List<Id> caseIds, List<String> fields) {
		String soql = new SoqlBuilder()
						  .selectx(fields)
						  .fromx(CASEx)
						  .wherex(new SetCondition('Id').inx(caseIds))
						  .toSoql();
		return Database.query(soql);
	}

	public static Case getWithServiceDatesById(Id caseId, List<String> caseFields, List<String> serviceDateFields) {
		String soql = new SoqlBuilder()
						  .selectx(caseFields)
						  .selectx(
						  	new SoqlBuilder()
						  		.selectx(serviceDateFields)
						  		.fromx(SERVICEDATESx))
						  .fromx(CASEx)
						  .wherex(new FieldCondition('Id').equals(caseId))
						  .toSoql();
		return Database.query(soql);
	}

	public static List<Case> getWithServiceDatesByIds(List<Id> caseIds, List<String> caseFields, List<String> serviceDateFields) {
		String soql = new SoqlBuilder()
						  .selectx(caseFields)
						  .selectx(
						  	new SoqlBuilder()
						  		.selectx(serviceDateFields)
						  		.fromx(SERVICEDATESx))
						  .fromx(CASEx)
						  .wherex(new SetCondition('Id').inx(caseIds))
						  .toSoql();
		return Database.query(soql);
	}

	public static List<Case> getWorkOrdersWithShipmentsByAccountId(Id accountId, List<String> caseFields, List<String> shipmentFields) {
		String soql = new SoqlBuilder()
						  .selectx(caseFields)
						  .selectx(
						  	new SoqlBuilder()
						  		.selectx(shipmentFields)
						  		.fromx(SHIPMENTSx))
						  .fromx(CASEx)
						  .wherex(new AndCondition()
						  			  .add(new FieldCondition('RecordType.Name').equals(new Constants.CaseRecordTypes().WORK_ORDERS))
						  			  .add(new FieldCondition('AccountId').equals(accountId)))
						  .toSoql();
		return Database.query(soql);
	}

	public static String getScopeOfWork(String clinicId, Case workOrder, Case installationApproval, String specialInstructions) {
		Constants.ScopesOfWork scope = new Constants.ScopesOfWork();
		String scopeOfWork = '';

		scopeOfWork += scope.TECHNICIAN_DUTIES_1; scopeOfWork +=' \r\n'; 

		scopeOfWork += scope.CONTEXTMEDIA_NDS +  installationApproval.account.NetworkDeploymentSpecialist__r.FirstName 
		+  ' ' + installationApproval.account.NetworkDeploymentSpecialist__r.LastName ;
		if (installationApproval.account.NetworkDeploymentSpecialist__r.Phone != null && installationApproval.account.NetworkDeploymentSpecialist__r.Phone <>''){
			scopeOfWork += ' - '+ installationApproval.account.NetworkDeploymentSpecialist__r.Phone;
		}
		scopeOfWork +=' \r\n\r\n '; 

		if (installationApproval.IT_Contact_Name__c != null && installationApproval.IT_Contact_Name__c != '') {
			scopeOfWork += scope.IT_CONTACT_NAME
						 + installationApproval.IT_Contact_Name__c + ' \r\n '
						 + scope.IT_CONTACT_EMAIL
						 + installationApproval.IT_Email_Address__c + ' \r\n '
						 + scope.IT_CONTACT_PHONE
						 + installationApproval.IT_Phone_Number__c + ' \r\n\r\n ';
		}				 


		if (specialInstructions != null && specialInstructions != '') {
			scopeOfWork += scope.SPECIAL_INSTRUCTIONS;
			scopeOfWork += specialInstructions + ' \r\n\r\n ';
		}

		scopeOfWork +=scope.WORK_ORDER + ' \r\n ';

		if (workOrder.TVs_Being_Installed__c != null && workOrder.TVs_Being_Installed__c != '') {
			scopeOfWork += scope.SCOPE_SCREENS + workOrder.TVs_Being_Installed__c;
		}
		if (workOrder.Players_Being_Installed__c != null && workOrder.Players_Being_Installed__c != '') {
			scopeOfWork += scope.SCOPE_PLAYERS + workOrder.Players_Being_Installed__c;
		}
		if (workOrder.Tablets_Being_Installed__c != null && workOrder.Tablets_Being_Installed__c != '') {
			scopeOfWork += scope.SCOPE_TABLETS + workOrder.Tablets_Being_Installed__c;
		}
		if (workOrder.Routers_Being_Installed__c != null && workOrder.Routers_Being_Installed__c != '') {
			scopeOfWork += scope.SCOPE_ROUTERS + workOrder.Routers_Being_Installed__c;
		}

		scopeOfWork += ' \r\n\r\n ';
		if (workOrder.TVs_Being_Installed__c != null && workOrder.TVs_Being_Installed__c != ''
				|| workOrder.Players_Being_Installed__c != null && workOrder.Players_Being_Installed__c != '' ) {
		scopeOfWork += scope.SCOPE_INTERNET_CONNECTION_TYPE + installationApproval.Recommended_Player_Type__c;
		scopeOfWork += ' \r\n\r\n ';
		}

		if (workOrder.Tablets_Being_Installed__c != null && workOrder.Tablets_Being_Installed__c != '') {
		scopeOfWork += scope.SCOPE_TABLET_CONNECTION_TYPE + installationApproval.TabletConnectionType__c;
		scopeOfWork += ' \r\n\r\n ';
		}

		scopeOfWork += scope.ClINIC_ID + clinicId;
		scopeOfWork += ' \r\n\r\n ';

		if (installationApproval.Best_Day_Time_etc_for_Install__c != null && installationApproval.Best_Day_Time_etc_for_Install__c != '') {
		scopeOfWork += scope.BEST_DAY_TIME_FOR_WORK_ORDER + installationApproval.Best_Day_Time_etc_for_Install__c;
		}

		return scopeOfWork;
	}

	public static void getDeinstallApproval(List<Case> cases) {
		List<Approval.ProcessSubmitRequest> approvalProcessRequests = new List<Approval.ProcessSubmitRequest>();
		for (Case theCase : cases) {
			if (theCase.Service__c == 'Full Deinstall') {
				Approval.ProcessSubmitRequest request = new Approval.ProcessSubmitRequest();
				request.setObjectId(theCase.id);
				approvalProcessRequests.add(request);
			}
		}
		if (ListUtils.isNotNullOrEmpty(approvalProcessRequests)) {
			List<Approval.ProcessResult> results = Approval.process(approvalProcessRequests);
		}
	}

	public static void getDeinstallApproval(Map<Id, Case> oldCases, List<Case> cases) {
		List<Approval.ProcessSubmitRequest> approvalProcessRequests = new List<Approval.ProcessSubmitRequest>();
		for (Case theCase : cases) {
			if (theCase.Service__c == new Constants.CaseServices().FULL_DEINSTALL && oldCases.get(theCase.Id).Service__c != new Constants.CaseServices().FULL_DEINSTALL) {
				Approval.ProcessSubmitRequest request = new Approval.ProcessSubmitRequest();
				request.setObjectId(theCase.id);
				approvalProcessRequests.add(request);
			}
		}
		if (ListUtils.isNotNullOrEmpty(approvalProcessRequests)) {
			List<Approval.ProcessResult> results = Approval.process(approvalProcessRequests);
		}
	}

	public static void validateWorkOrderClosure(Map<Id, Case> oldSoMap, List<Case> soList) {
		Map<Id, Schema.RecordTypeInfo> recordTypes = Schema.getGlobalDescribe().get(CASEx).getDescribe().getRecordTypeInfosById();

		if (soList.size() == 1) {
			system.debug('Record Type: ' + recordTypes.get(soList[0].RecordTypeId).getName());
			if (recordTypes.get(soList[0].RecordTypeId).getName() == new Constants.CaseRecordTypes().WORK_ORDERS && soList[0].Status == new Constants.CaseStatuses().CLOSED && oldSoMap.get(soList[0].Id).Status != new Constants.CaseStatuses().CLOSED && soList[0].AccountId != null) {
				validateWorkOrderClosure(String.valueOf(soList[0].CMH_ID__c), soList[0].Id);
			}
		}
	}

	@future(callout=true)
	private static void validateWorkOrderClosure(String clinicId, Id workOrderId) {
		Map<String, Object> mdmResponse;
		Map<String, Object> mdmDevices = new Map<String, Object>();
		Map<String, Object> broadsignResponse;
		try {
			mdmResponse = MdmDelegate.getMdmStatusesByClinicId(clinicId);
			Object devicesObject;
			if (mdmResponse != null) {
				devicesObject = mdmResponse.get('devices');
			}
			if (devicesObject != null) {
				List<Object> devicesObjects = (List<Object>)devicesObject;
				for (Object device : devicesObjects) {
					Map<String, Object> deviceMap = (Map<String, Object>)device;
					for (String value : deviceMap.keySet()) {
						mdmDevices.put(value, deviceMap.get(value));
					}
				}
			}

			broadsignResponse = BroadsignDelegate.getBroadsignStatusesByClinicId(clinicId);
		}
		catch (MdmException ex) {
			EmailUtils.sendTextEmail(new List<String> {'matt.t@contextmediainc.com'}, 'Work Order Closure Mdm Exception', ex.getMessage());
		}
		catch (BroadsignException ex) {
			EmailUtils.sendTextEmail(new List<String> {'matt.t@contextmediainc.com'}, 'Work Order Closure Broadsign Exception', ex.getMessage());
		}
		catch (CalloutException ex) {
			EmailUtils.sendTextEmail(new List<String> {'matt.t@contextmediainc.com'}, 'Work Order Closure Callout Exception', ex.getMessage());
		}

		List<Asset> assetsToProcess = new List<Asset>();
		List<Asset> unknownAssets = new List<Asset>();
		List<Asset> assets = AssetService.getByRelatedWorkOrderId(workOrderId, new List<String> {'Name',
																								 'Shipment__c',
																								 'Status',
																								 'Type__c'});
		if (ListUtils.isNotNullOrEmpty(assets)) {
			for (Asset asset : assets) {
				if (asset.Status == 'Installed' && asset.Shipment__c == null) {
					if (asset.Type__c == new Constants.AssetTypes().TABLET) {
						if (mdmDevices.get(asset.Name) != null) {
							Map<String, Object> tabletResponse = (Map<String, Object>)mdmDevices.get(asset.Name);
							system.debug('Asset ' + asset.Name + ' is ' + tabletResponse.get('device_status'));
							if (tabletResponse.get('device_status') != 'up') {
								assetsToProcess.add(asset);
							}
						}
						else {
							unknownAssets.add(asset);
						}
					}
					else if (asset.Type__c == new Constants.AssetTypes().PLAYER) {
						if (broadsignResponse == null || broadsignResponse.get('error') != null) {
							unknownAssets.add(asset);
						}
						else {
							if (broadsignResponse.get(asset.Name) != null) {
								Map<String, Object> playerResponse = (Map<String, Object>)broadsignResponse.get(asset.Name);
								if ((String)playerResponse.get('status') != '1') {
									assetsToProcess.add(asset);
								}
							}
							else {
								unknownAssets.add(asset);
							}
						}
					}
				}
			}
		}

		if (ListUtils.isNotNullOrEmpty(assetsToProcess) || ListUtils.isNotNullOrEmpty(unknownAssets)) {
			Case workOrder = CaseService.getById(workOrderId, new List<String> {'Account.CMHID__c',
																				'Account.Name',
																				'CaseNumber',
																				'CreatedBy.Email',
																				'Owner.Email',
																				'Product__c',
																				'Service__c',
																				'Type'});
			workOrder.Status = 'Reopened';
			try {
				update workOrder;
				String emailBody = 'The ' + workOrder.Product__c + ' ' + workOrder.Service__c + ' work order for '
								 + workOrder.Account.Name + ' (' + clinicId + ') was closed but has been reopened because the following assets are either not online or were not found:  <br/><br/>';
				if (ListUtils.isNotNullOrEmpty(assetsToProcess)) {
					emailBody += '<strong>Offline Assets:</strong><br/>';
					for (Asset asset : assetsToProcess) {
						emailBody += asset.Name + ' - ' + asset.Type__c + ': <br/>'
								   + Url.getSalesforceBaseUrl().toExternalForm() + '/' + asset.Id + '<br/><br/>';
					}
				}
				if (ListUtils.isNotNullOrEmpty(unknownAssets)) {
					emailBody += '<strong>Unknown Assets:</strong><br/>';
					for (Asset asset : unknownAssets) {
						emailBody += asset.Name + ' - ' + asset.Type__c + ': <br/>'
								   + Url.getSalesforceBaseUrl().toExternalForm() + '/' + asset.Id + '<br/><br/>';
					}
				}
				emailBody += 'Please ensure these devices are online prior to closing the work order again. Here is a link to the work order: '
						   + Url.getSalesforceBaseUrl().toExternalForm() + '/' + workOrder.Id;
				EmailUtils.sendHtmlEmail(new List<String> {workOrder.Owner.Email, workOrder.CreatedBy.Email, 'matt.t@contextmediainc.com'}, 'Work Order ' + workOrder.CaseNumber + ' - Reopened', emailBody);
			}
			catch (DmlException ex) {
				EmailUtils.sendTextEmail(new List<String> {'matt.t@contextmediainc.com'}, 'DmlException in work order closure validation', ex.getMessage());
			}
		}
		else {
			system.debug('All Assets are ONLINE.');
		}
	}
}