src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Qualification_Type__c</fullName>
        <description>This field is maintained only from the contact triggers when a contact accountId changes.</description>
        <globalPicklist>Qualification_Type</globalPicklist>
        <label>Qualification Type</label>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>NPI__c</fullName>
        <label>NPI #</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Qualification_Type__c</fullName>
        <description>In their list of qualifications, if they have at least one of the Speciality qualifications listed below, set their Qualification Type to &quot;Specialty&quot;
In their list of qualifications, if they don&apos;t have any Specialty qualifications listed below but have at least one PCP qualification, set their Qualification Type to &quot;PCP&quot;
In their list of qualifications, if they don&apos;t have any Specialty or PCP qualifications listed below but have at least one General Health qualification, set their Qualification Type to &quot;General Health&quot;
In their list of qualifications, if they don&apos;t have any Specialty, PCP or General Health qualifications listed below, set their Qualification Type to &quot;None&quot;.</description>
        <label>Qualification Type</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Specialty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PCP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Health</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Qualification__c</fullName>
        <label>Qualification</label>
        <picklist>
            <picklistValues>
                <fullName>Allergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gastroenterology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infectious Disease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neurology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obstetrics and Gynecology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oncology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rheumatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Urology</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Qualification__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to indicate which products should have commission applied to them for the given qualification and if a multiplier should be applied.</description>
    <fields>
        <fullName>Qualification_Type__c</fullName>
        <label>Qualification Type</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Qualification</label>
</CustomObject>

src/classes/ContactService.cls
public without sharing class ContactService {

	private static final String ACCOUNTCONTACTROLEx = 'AccountContactRole';
	private static final String CONTACTx = 'Contact';
	private static final String ACCOUNTx = 'Account';
	private static final String CONTACTSx = 'Contacts';

	public static Contact getById(Id contactId, List<String> fields) {
		String soql = new SoqlBuilder()
						  .selectx(fields)
						  .fromx(CONTACTx)
						  .wherex(new FieldCondition('Id').equals(contactId))
						  .toSoql();
		return Database.query(soql);
	}

	public static List<Contact> getByIds(List<Id> contactIds, List<String> fields) {
		String soql = new SoqlBuilder()
						  .selectx(fields)
						  .fromx(CONTACTx)
						  .wherex(new SetCondition('Id').inx(contactIds))
						  .toSoql();
		return Database.query(soql);
	}

	public static List<AccountContactRole> getAccountContactRolesByContactId(Id contactId, List<String> fields) {
		String soql = new SoqlBuilder()
						  .selectx(fields)
						  .fromx(ACCOUNTCONTACTROLEx)
						  .wherex(new FieldCondition('ContactId').equals(contactId))
						  .toSoql();
		return Database.query(soql);
	}

	/*******************************************************************************************************
	* @description   Return a map of accountId as the key and a list of related Accounts with NPI contacts as the list
	* 
	* @return 		[Map<Id, Account>]
	* 
	*/
	public static Map<Id, Account> getNpiContactForAccountIds(List<Id> accountIds, List<String> accountFields, List<String> contactFields){
		
		String soql = new SoqlBuilder()
						    .selectx(accountFields)
					    	.selectx(
						        new SoqlBuilder()
						        	.selectx(contactFields)
						    		.fromx(CONTACTSx))
						    		.wherex(new FieldCondition('Npi__c').notEquals(null))
						    .fromx(ACCOUNTx)
						    .wherex(new SetCondition('Id').inx(accountIds))
						    .toSoql();
		
		List<Account> accounts = Database.query(soql);

		if (ListUtils.isNotNullOrEmpty(accounts)) {
			return new Map<Id, Account>(accounts);
		}
		return null;
	}

	/*******************************************************************************************************
	* @description 		Method updates Contact.Qualification_Type__c picklist field based on the ; delimitted
	*                	values in the Contact.Qualification__c field. It determines what qualification type
	*                	is by the mappings in Custom Setting Qualificaiton__c where we also have priorities
	*                	setup for each qualification and qualificaiton type
	* 
	* @param 			[List<Contact>] List of contacts source from before insert/update trigger context 
	* @return 			void
	* 
	*/
	public static void calculateQualificationType(List<Contact> newContactsList) {
		for (Contact contact :newContactsList) {
			if (contact.NPI__c != null && String.isNotEmpty(contact.Qualification__c)) {
				setQualificationTypeForContact(contact, contact.Qualification__c.split(';'));
			}
		}
	}

	/*******************************************************************************************************
	* @description 		Method sets the Qualification Type field for given list of qulificaitons and a contact
	* 
	*/
	@TestVisible
	private static void setQualificationTypeForContact(Contact contact, List<String> qualifications) {
		Integer highestPriority = CommissionUtils.getInstance().findHighestPriority(qualifications);
		contact.Qualification_Type__c = CommissionUtils.getInstance().priorityToQualificationTypeMap.get(highestPriority);
	}
}