src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>RelatedWorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Work Order</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>Order ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelatedWorkOrder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Work Order</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isExpedited__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expedited</label>
        <type>Checkbox</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShipmentItem__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipLabel>Shipment Items</relationshipLabel>
        <relationshipName>Shipment_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Shipment Item</label>
    <nameField>
        <label>Shipment Item SKU</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ShipmentServiceTest.cls
@isTest
private class ShipmentServiceTest {
	
	private static testMethod void testGetWithShipmentItemsByOrderId() {
		Account account = new Account();
		account.Name = 'Account Name';
		insert account;
		Shipment__c shipment = new Shipment__c();
		shipment.OrderId__c = '12345';
		shipment.Account__c = account.Id;
		insert shipment;
		ShipmentItem__c item = new ShipmentItem__c();
		item.Quantity__c = 1;
		item.Shipment__c = shipment.Id;
		insert item;

		Shipment__c result = ShipmentService.getWithShipmentItemsByOrderId('12345', new List<String> {'Account__c',
																									  'OrderId__c'}, new List<String> {'Quantity__c',
																									  								   'Shipment__c'});
		system.assert(result.Id == shipment.Id);
		system.assert(ListUtils.isNotNullOrEmpty(result.Shipment_Items__r));
	}

	private static testMethod void testGetWithShipmentItemsAndAssetsByCaseId() {
		Account account = new Account();
		account.Name = 'Account Name';
		insert account;
		Case workOrder = new Case();
		workOrder.AccountId = account.Id;
		insert workOrder;
		Shipment__c shipment = new Shipment__c();
		shipment.OrderId__c = '12345';
		shipment.Account__c = account.Id;
		shipment.RelatedWorkOrder__c = workOrder.Id;
		insert shipment;
		Asset asset = new Asset();
		asset.Name = 'Asset Name';
		asset.AccountId = account.Id;
		asset.Shipment__c = shipment.Id;
		insert asset;
		ShipmentItem__c item = new ShipmentItem__c();
		item.Quantity__c = 1;
		item.Shipment__c = shipment.Id;
		insert item;

		List<Shipment__c> results = ShipmentService.getWithShipmentItemsAssetsShipmentPackagesByCaseId(workOrder.Id, new List<String> {'Account__c',
																														 'OrderId__c',
																														 'RelatedWorkOrder__c'},
																									   new List<String> {'Quantity__c',
																									   					 'Shipment__c'},
																									   new List<String> {'AccountId',
																									   					 'Name'},
																									   new List<String> {'Id'});
		for (Shipment__c result : results) {
			system.assert(result.Id == shipment.Id);
			system.assert(ListUtils.isNotNullOrEmpty(result.Shipment_Items__r));
			system.assert(ListUtils.isNotNullOrEmpty(result.Assets__r));
		}
	}

	private static testMethod void testGetWithShipmentItemsAndAssetsByAccountIdOnly() {
		Account account = new Account();
		account.Name = 'Account Name';
		insert account;
		Case workOrder = new Case();
		workOrder.AccountId = account.Id;
		insert workOrder;
		Shipment__c shipment = new Shipment__c();
		shipment.OrderId__c = '12345';
		shipment.Account__c = account.Id;
		insert shipment;
		Asset asset = new Asset();
		asset.Name = 'Asset Name';
		asset.AccountId = account.Id;
		asset.Shipment__c = shipment.Id;
		insert asset;
		ShipmentItem__c item = new ShipmentItem__c();
		item.Quantity__c = 1;
		item.Shipment__c = shipment.Id;
		insert item;

		List<Shipment__c> results = ShipmentService.getWithShipmentItemsAssetsShipmentPackagesByAccountIdOnly(account.Id, new List<String> {'Account__c',
																															   'OrderId__c',
																															   'RelatedWorkOrder__c'},
																											 new List<String> {'Quantity__c',
																									   						   'Shipment__c'},
																											 new List<String> {'AccountId',
																									   						   'Name'},
																									   		 new List<String> {'Id'});
		for (Shipment__c result : results) {
			system.assert(result.Id == shipment.Id);
			system.assert(ListUtils.isNotNullOrEmpty(result.Shipment_Items__r));
			system.assert(ListUtils.isNotNullOrEmpty(result.Assets__r));
		}
	}

	private static testMethod void testGetActiveProducts() {
		List<Product2> products = ShipmentService.getActiveProducts(new List<String> {'ProductCode'});
	}

	private static testMethod void testGetCustomPricebooksWithPricebookEntries() {
		List<Pricebook2> pricebooks = ShipmentService.getCustomPricebooksWithPricebookEntries(new List<String> {'Id'}, new List<String> {'Id'});
	}

	private static testMethod void testValidate() {
		Account account = new Account();
		account.Name = 'Account Name';
		insert account;
		Contact contact = new Contact();
		contact.FirstName = 'First Name';
		contact.LastName = 'Last Name';
		contact.AccountId = account.Id;
		insert contact;
		Shipment shipment = new Shipment(account);
		shipment.shipment.isExpedited__c = true;

		List<String> result = ShipmentService.validate(shipment, account, contact);
		for(String s : result) {
			system.debug(s);
		}
		

		system.assert(ListUtils.isNotNullOrEmpty(result), 'Errors should have been generated');
		system.assertEquals(new Constants.ShipmentValidationMessages().EXPEDITE_REASON, result[0], 'Incorrect error message');
		system.assertEquals(new Constants.ShipmentValidationMessages().REQUESTED_DATE, result[1], 'Incorrect error message');
		system.assertEquals(new Constants.ShipmentValidationMessages().ADDRESS_INCOMPLETE, result[2], 'Incorrect error message');
		system.assertEquals(new Constants.ShipmentValidationMessages().ITEMS_TO_RETURN, result[3], 'Incorrect error message');
		system.assertEquals(new Constants.ShipmentValidationMessages().PRIMARY_CONTACT, result[4], 'Incorrect error message');
		system.assertEquals(new Constants.ShipmentValidationMessages().CMH_ID, result[5], 'Incorrect error message');
		system.assertEquals(new Constants.ShipmentValidationMessages().DMA_ZIP, result[6], 'Incorrect error message');
		system.assertEquals(new Constants.ShipmentValidationMessages().DMA_TIMEZONE, result[7], 'Incorrect error message');
		system.assertEquals(new Constants.ShipmentValidationMessages().NETWORK, result[8], 'Incorrect error message');


	}
}