src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>OutletLock__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether or not the given Asset was installed with an outlet lock.</description>
        <label>Outlet Lock</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Player</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Sprint Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cradle Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Verizon Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verizon USB Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wifi Hotspot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Type1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/CaseDetailsActions.cls
public virtual class CaseDetailsActions {
	@RemoteAction
	public static Map<String, Object> getOptions(Id caseId) {
		try {
			Case thisCase = CaseService.getWithServiceDatesById(caseId, new List<String> {'AccountId',
																						  'Status'}, new List<String> {'Technician_Name__c'});

			List<Asset> thisAssets = AssetService.getByRelatedWorkOrderId(thisCase.Id, new List<String> {	'Id',
																								 			'Name',
																								 			'OutletLock__c',
																								 			'Outlet_Lock_Reason__c',
																								 			'Product2.ProductCode',
																								 			'Status',
																								 			'Type__c'});

			List<String> outletLockReasons = new List<String>();
	        
	        List<Schema.PicklistEntry> outletLockReasonEntries = Asset.Outlet_Lock_Reason__c.getDescribe().getPicklistValues();
	        
	        for (Schema.PicklistEntry entry : outletLockReasonEntries) {
	            outletLockReasons.add(entry.getValue());
	        }

	        return new Map<String, Object> {
	        	'assets' => thisAssets,
	        	'case' => thisCase,
	        	'outletLockReasons' => outletLockReasons
	        };
		}
		catch (Exception ex) {
			 throw ex;
		}
		return null;
	}

	@RemoteAction
	public static void close(Id caseId, List<Asset> assets) {
		try {
			Case thisCase = new Case(Id = caseId, Status = 'Closed');
			update thisCase;
			update assets;
		}
		catch (DmlException ex) {
			throw ex;
		}
	}
}