src/objects/Asset.object
<CustomObject>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <picklist>
            <controllingField>Make__c</controllingField>
            <picklistValues>
                <fullName>20LS7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LT560C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22LV255C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>250U - Sprint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LC7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LD352C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LH20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26LT560C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LC7DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD350C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD452B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LH20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LN541C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LT560E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>32LV255C - LED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD450C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD452B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>37LT560E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD450C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD452B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LD452C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LG30DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LN541C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>42LT560E</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OS__c</fullName>
        <label>OS</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>7.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8.04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9.10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10.04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12.04</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Win 7 Pro - OEM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Player_location_at_site__c</fullName>
        <inlineHelpText>This field is only required for clinics with more than 1 system</inlineHelpText>
        <label>Player location at site</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Display</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Player</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Sprint Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cradle Point</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USB Verizon Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verizon USB Modem</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tablet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wifi Hotspot</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InlineAssetController.cls
/*
 * Created By : Lister
 * Created Date : 3-Apr-2014
 * Created Purpose : Extension controller class Inline Asset page
 * Test Class : TestAssetInline
 */
public with sharing class InlineAssetController {
    public final Case CASEx {get; set;}
    public List<Asset> assets {get; set;}
    public String assetId {get; set;}
    public String accountId {get; set;}
    public String assetIdEdit {get; set;} 
    
    public PageReference editAsset(){
        PageReference pageRef = new PageReference('/'+AssetIdEdit+'/e?retURL=%2F'+AssetIdEdit);
        pageRef.setRedirect(true);
        return pageRef ;
    }
    
    public InlineAssetController(ApexPages.StandardController standardController){
        Id CaseId = standardController.getRecord().Id;
        this.CASEx = [select Id, AccountId from Case where Id =:CaseId ];
        assets = new List<Asset>();
        assets = [select    Id, 
                            AccountId,
                            Model__c,  
                            Name, 
                            OS__c,
                            Outlet_Lock_Reason__c,
                            Player_location_at_site__c,
                            SerialNumber,
                            Status, 
                            Type__c
                    from Asset 
                    where AccountId =:CASEx.AccountId];
    }
    
}