src/objects/Case_Note__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Notes</relationshipLabel>
        <relationshipName>Case_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Note_Body__c</fullName>
        <label>Note Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Priority</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Note</label>
    <nameField>
        <displayFormat>CaseNote {00000}</displayFormat>
        <label>Case Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseNotesClassTest.cls
@isTest
private class CaseNotesClassTest {

    static testMethod void myUnitTest() {
		
		Case c = new Case();
		insert c;
		
		
		Case_Note__c n1 = new Case_Note__c(Case__c = c.Id,  Priority__c = true, Note_Body__c = 'test');
		Case_Note__c n2 = new Case_Note__c(Case__c = c.Id,  Priority__c = false, Note_Body__c = 'test');
		
		List <Case_Note__c> notes = new List <Case_Note__c>();
		
		notes.add(n1);
		notes.add(n2);
		
		insert notes;
		
		PageReference pageRef = Page.CaseNotesPage;
		pageRef.getParameters().put('id', c.Id);
		Test.setCurrentPage(pageRef);
		
		ApexPages.StandardController controller = new ApexPages.StandardController(c);
        CaseNotesClass sc = new CaseNotesClass(controller);
        
        string caseNOtes = sc.notes;
    }
}