src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>IT_Contact_Name__c</fullName>
        <label>IT Contact Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IT_Email_Address__c</fullName>
        <label>IT Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IT_Phone_Number__c</fullName>
        <label>IT Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Players_Being_Installed__c</fullName>
        <label># Players Being Installed</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Routers_Being_Installed__c</fullName>
        <label>Routers Being Installed</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TVs_Being_Installed__c</fullName>
        <label># TVs Being Installed</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tablets_Being_Installed__c</fullName>
        <label># Tablets Being Installed</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Cases</fullName>
        <active>true</active>
        <businessProcess>Cases and Changes</businessProcess>
        <description>Account Management, Affiliate Office Sale, Content Request, Deinstallation, IT Approval, Missing Equipment, Other, Player MIA in BS, Potential Upgrade, Reported Issue, Shipping Issue and New Sale Cases.</description>
        <label>Cases</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Date__c.object
<CustomObject>
    <description>Service Dates for Work Orders</description>
    <fields>
        <fullName>Related_Work_Order__c</fullName>
        <label>Related Work Order</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Dates</relationshipLabel>
        <relationshipName>Service_Dates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Service Date</label>
    <nameField>
        <displayFormat>ServiceDate-{000000}</displayFormat>
        <label>Service Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseServiceTest.cls
@isTest
private class CaseServiceTest {
	
	private static testmethod void testGetById() {
		Case test = new Case();
		insert test;
		Case result = CaseService.getById(test.Id, new List<String> {'Id'});

		system.assert(test == result);
	}

	private static testmethod void testGetByIds() {
		List<Id> caseIds = new List<Id>();
		List<Case> cases = new List<Case>();
		Case test = new Case();
		insert test;
		caseIds.add(test.Id);
		cases.add(test);
		List<Case> result = CaseService.getByIds(caseIds, new List<String> {'Id'});

		system.assert(result == cases);
	}

	private static testmethod void testGetWithServiceDatesById() {
		Case test = new Case();
		insert test;
		Service_Date__c serviceDate = new Service_Date__c();
		serviceDate.Related_Work_Order__c = test.Id;
		insert serviceDate;
		Case result = CaseService.getWithServiceDatesById(test.Id, new List<String> {'Id'}, new List<String> {'Id'});

		system.assert(test.Id == result.Id);
		system.assert(result.Service_Dates__r.size() == 1);
	}

	private static testmethod void testGetWithServiceDatesByIds() {
		List<Id> caseIds = new List<Id>();
		Case test = new Case();
		insert test;
		Service_Date__c serviceDate = new Service_Date__c();
		serviceDate.Related_Work_Order__c = test.Id;
		insert serviceDate;
		caseIds.add(test.Id);
		List<Case> result = CaseService.getWithServiceDatesByIds(caseIds, new List<String> {'Id'}, new List<String> {'Id'});

		system.assert(result[0].Id == test.Id);
		system.assert(result[0].Service_Dates__r.size() == 1);
	}

	private static testmethod void testGetScopeOfWork() {
		Case workOrder = new Case();
		workOrder.TVs_Being_Installed__c = '1';
		workOrder.Players_Being_Installed__c = '1';
		workOrder.Tablets_Being_Installed__c = '1';
		workOrder.Routers_Being_Installed__c = '1';
		insert workOrder;
		Case installationApproval = new Case();
		installationApproval.IT_Contact_Name__c = 'Bob';
		installationApproval.IT_Phone_Number__c = '1234567890';
		installationApproval.IT_Email_Address__c = 'bob@bob.bob';

		Constants.ScopesOfWork scope = new Constants.ScopesOfWork();
		String scopeOfWork = CaseService.getScopeOfWork('1234', workOrder, installationApproval, 'Special Instructions');

		system.assert(scopeOfWork.contains(scope.IT_CONTACT_NAME));
		system.assert(scopeOfWork.contains(scope.IT_CONTACT_EMAIL));
		system.assert(scopeOfWork.contains(scope.IT_CONTACT_PHONE));
		system.assert(scopeOfWork.contains(scope.SCOPE_SCREENS));
		system.assert(scopeOfWork.contains(scope.SCOPE_PLAYERS));
		system.assert(scopeOfWork.contains(scope.SCOPE_TABLETS));
		system.assert(scopeOfWork.contains(scope.SCOPE_ROUTERS));
		system.assert(scopeOfWork.contains(scope.SPECIAL_INSTRUCTIONS));
	}
}