src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Checked_In__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked In, Yes from the latest service date on a Work Orders Case.</description>
        <label>Checked In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Checked_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked Out, Yes from the latest service date on a Work Orders Case.</description>
        <label>Checked Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CheckinTime__c</fullName>
        <label>Check-in Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CheckoutTime__c</fullName>
        <label>Check-out Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LatestServiceDateEnd__c</fullName>
        <label>Latest Service Date - End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LatestServiceDateStart__c</fullName>
        <label>Latest Service Date - Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TechName__c</fullName>
        <label>Tech Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Cases</fullName>
        <active>true</active>
        <businessProcess>Cases and Changes</businessProcess>
        <description>Account Management, Affiliate Office Sale, Content Request, Deinstallation, IT Approval, Missing Equipment, Other, Player MIA in BS, Potential Upgrade, Reported Issue, Shipping Issue and New Sale Cases.</description>
        <label>Cases</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service_Date__c.object
<CustomObject>
    <description>Service Dates for Work Orders</description>
    <fields>
        <fullName>CheckInTime__c</fullName>
        <label>Check In Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CheckOutTime__c</fullName>
        <label>Check Out Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CheckedInYES__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checked In, YES</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CheckedOutYES__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checked Out, YES</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Work_Order__c</fullName>
        <label>Related Work Order</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Service Dates</relationshipLabel>
        <relationshipName>Service_Dates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ServiceDateEnd__c</fullName>
        <label>Service Date - End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ServiceDateStart__c</fullName>
        <label>Service Date - Start</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Technician_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technician Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Name</field>
                <operation>equals</operation>
                <value>ContextMedia Contractors</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Service Dates</relationshipLabel>
        <relationshipName>Service_Dates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Date</label>
    <nameField>
        <displayFormat>ServiceDate-{000000}</displayFormat>
        <label>Service Date Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ServiceDateService.cls
public class ServiceDateService {
	private static final String SERVICEDATEx = 'Service_Date__c';

	public static void updateFurthestServiceDateInformation(List<Service_Date__c> serviceDates) {
		if (ListUtils.isNullOrEmpty(serviceDates)) {
			return;
		}
		List<Id> caseIds = new List<Id>();
		for (Service_Date__c serviceDate : serviceDates) {
			caseIds.add(serviceDate.Related_Work_Order__c);
		}
		List<Case> cases = CaseService.getWithServiceDatesByIds(caseIds, new List<String> { 'Id',
																							'LatestServiceDateEnd__c',
																							'LatestServiceDateStart__c'}, new List<String> { 'Id',
																																			 'CheckedInYES__c',
																																			 'CheckedOutYES__c',
																																			 'CheckInTime__c',
																																			 'CheckOutTime__c',
																																			 'ServiceDateEnd__c',
																																			 'ServiceDateStart__c',
																																			 'Technician_Name__r.Name'});
		Service_Date__c furthestServiceDate;
		List<Case> casesToUpdate = new List<Case>();
		for (Case workOrder : cases) {
			furthestServiceDate = getFurthestServiceDateByCase(workOrder);
			if (furthestServiceDate == null) {
				workOrder.LatestServiceDateStart__c = null;
				workOrder.LatestServiceDateEnd__c = null;
				workOrder.Checked_In__c = false;
				workOrder.Checked_Out__c = false;
				workOrder.CheckInTime__c = null;
				workOrder.CheckOutTime__c = null;
				workOrder.TechName__c = null;
				casesToUpdate.add(workOrder);
				continue;
			}
			else {
				workOrder.LatestServiceDateStart__c = furthestServiceDate.ServiceDateStart__c;
				workOrder.LatestServiceDateEnd__c = furthestServiceDate.ServiceDateEnd__c;
				workOrder.Checked_In__c = furthestServiceDate.CheckedInYES__c;
				workOrder.Checked_Out__c = furthestServiceDate.CheckedOutYES__c;
				workOrder.CheckInTime__c = furthestServiceDate.CheckInTime__c == null ? null : String.valueOf(furthestServiceDate.CheckInTime__c.format('MM/dd/yyyy hh:mm a'));
				workOrder.CheckOutTime__c = furthestServiceDate.CheckOutTime__c == null ? null : String.valueOf(furthestServiceDate.CheckOutTime__c.format('MM/dd/yyyy hh:mm a'));
				workOrder.TechName__c = furthestServiceDate.Technician_Name__r.Name;
				casesToUpdate.add(workOrder);
			}
		}
		if (ListUtils.isNotNullOrEmpty(casesToUpdate)) {
			try {
				update casesToUpdate;
			}
			catch(DmlException ex) {
				EmailUtils.sendTextEmail(new List<String> { 'matt.t@contextmediainc.com' }, 'ProductService DmlException', ex.getMessage());
			}
		}
	}


	public static Service_Date__c getById(Id serviceDateId, List<String> fields) {
		String soql = new SoqlBuilder()
						  .selectx(fields)
						  .fromx(SERVICEDATEx)
						  .wherex(new FieldCondition('Id').equals(serviceDateId))
						  .toSoql();
		return Database.query(soql);
	}


	public static Service_Date__c getFurthestServiceDateByCase(Case workOrder) {
		Service_Date__c furthestServiceDate;

		if (ListUtils.isNullOrEmpty(workOrder.Service_Dates__r)) {
			return null;
		}
		else if (workOrder.Service_Dates__r.size() == 1) {
			return workOrder.Service_Dates__r[0];
		}
		else {
			for (Service_Date__c serviceDate : workOrder.Service_Dates__r) {
				if (furthestServiceDate == null) {
					furthestServiceDate = serviceDate;
					continue;
				}
				if (serviceDate.ServiceDateStart__c > furthestServiceDate.ServiceDateStart__c) {
					furthestServiceDate = serviceDate;
				}
			}
		}
		return furthestServiceDate;
	}


	/*******************************************************************************************************
    * @description      Check to see if ServiceDateEnd__c is within business hours and adds a DML error if
    *					it does not.
    * 
    * @return           void
    */
	public static void checkInstallBlackoutDates(List<Service_Date__c> serviceDates) {
		checkInstallBlackoutDates(null, serviceDates);
	}

	/*******************************************************************************************************
    * @description      Check to see if ServiceDateEnd__c is within business hours and adds a DML error if
    *					it does not.
    * 
    * @return           void
    */
	public static void checkInstallBlackoutDates(Map<Id, Service_Date__c> oldServiceDates, List<Service_Date__c> serviceDates) {
		if (ListUtils.isNullOrEmpty(serviceDates)) {
			return;
		}
		try {
			BusinessHours installDays = BusinessHoursService.getByName(new Constants.BusinessHours().INSTALL_DAYS, new List<String> {'Id','TimeZoneSidKey'});
			if (installDays != null) {
				for (Service_Date__c serviceDate : serviceDates) {
					if (serviceDate.ServiceDateEnd__c != null && (oldServiceDates == null || serviceDate.ServiceDateEnd__c != oldServiceDates.get(serviceDate.Id).ServiceDateEnd__c) && !BusinessHours.isWithin(installDays.id, serviceDate.ServiceDateEnd__c)) {
						serviceDate.addError('Date Not Available for Install');
					}
				}
			} else {
				// LoggingUtils.log(new LoggingUtils.LogInfo(new ServiceDateServiceException('BusinessHours Install Days not found')), true, true, true);  // waiting on SAL-92
				// don't stop user
			}
		} catch (exception e) {
			// LoggingUtils.log(new LoggingUtils.LogInfo(e), true, true, true);  // waiting on SAL-92
			// don't stop user
		}
	
	}

	public class ServiceDateServiceException extends Exception {}
}