src/objects/Case_Note__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Notes</relationshipLabel>
        <relationshipName>Case_Notes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Note_Body__c</fullName>
        <label>Note Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Priority</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Note</label>
    <nameField>
        <displayFormat>CaseNote {00000}</displayFormat>
        <label>Case Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Notes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseNotesClass.cls
public with sharing class CaseNotesClass {
	
	private final Case thisCase;
    
    public CaseNotesClass(ApexPages.StandardController stdController) {
        this.thisCase = (Case)stdController.getRecord();
    }
    
	public string notes {
		get {
				if (String.isBlank(notes)) {
					
					notes = '';
					
					for (Case_Note__c cn : [
						SELECT Note_Body__c, Priority__c, CreatedBy.Name, Createddate
						FROM Case_Note__c 
						WHERE Case__c = :thisCase.Id
						ORDER BY CreatedDate ASC
						]) {
						
						string color = (cn.Priority__c) ? 'red' : 'black';
						
						notes += '<p/>'
						+ '<font color = \'' + color + '\' >' 
						+ '--- Created by <b>' 
						+ cn.CreatedBy.Name 
						+ '</b> on <b>' 
						+  cn.Createddate.format('M/d/yyyy h:mm a')
						+ '</b><br/>';
						
						notes += cn.Note_Body__c + '</font>';
						
					}
				}
			
			return notes;
		}
		set;
	}
	
}