src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Specialty__c</fullName>
        <label>Specialty</label>
        <picklist>
            <picklistValues>
                <fullName>Adolescent Medicine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Medicine/Pediatrics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Allergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ambulatory Medicine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anesthesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APRN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Audiologist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bariatrics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bariatric Surgeon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cardiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Operating Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Psychiatry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chiropractic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRNP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dentistry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dermatology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diabetology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dietician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Medicine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endocrinology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Epidemiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Practice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gastroenterology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Surgery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geriatric Psychiatry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geriatrics</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <picklist>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Office Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accountant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrative Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admissions Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aesthetician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Area Practice Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ARNP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant IT Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assistant Office Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Maintanence Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Development Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CEO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Dental Officer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chief Medical Officer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AddProductsController.cls
public with sharing class AddProductsController {
	public Opportunity opportunity {get;set;}
	public Account superParent {get;set;}

	public AddProductsController(ApexPages.StandardController standardController) {
		if (!Test.isRunningTest()) {
			standardController.addFields(new List<String> {'AccountId',
														   'Account.Name',
														   'CloseDate',
														   'Description',
														   'Name',
														   'Pricebook2Id',
														   'Pricebook2.Name',
														   'Probability',
														   'StageName'});
		}
		opportunity = (Opportunity)standardController.getRecord();
		//TODO: Default the opportunity's pricebook if there isn't one selected when this page is initialized.

		superParent = AccountService.getSuperParent(opportunity.AccountId, new List<String> {'Id', 'Name', 'ParentId'});
	}

	@RemoteAction
	public static Map<String, Object> getOptions(Id pricebookId) {
		Map<String, Object> result = new Map<String, Object>();

		List<String> specialtyValues = new List<String>();
		List<Schema.PicklistEntry> specialtyEntries = Contact.Specialty__c.getDescribe().getPicklistValues();
		for (Schema.PicklistEntry entry : specialtyEntries) {
			specialtyValues.add(entry.getValue());
		}
		result.put('specialties', specialtyValues);

		List<String> titleValues = new List<String>();
		List<Schema.PicklistEntry> titleEntries = Contact.Title__c.getDescribe().getPicklistValues();
		for (Schema.PicklistEntry entry : titleEntries) {
			titleValues.add(entry.getValue());
		}
		result.put('titles', titleValues);

		Map<String, String> productValues = new Map<String, String>();
		List<PricebookEntry> entries = ProductService.getPricebookEntriesByPricebookId(pricebookId, new List<String> {'Product2.ProductCode'});
		if (ListUtils.isNotNullOrEmpty(entries)) {
			for (PricebookEntry entry : entries) {
				productValues.put(entry.Product2.ProductCode, entry.Id);
			}
		}
		result.put('products', productValues);

		return result;
	}
}