src/objects/Exception_Log__c.object
<CustomObject>
    <description>Custom object used to store caught exceptions. Workflow rules can be leveraged to send email alerts upon record creation, and Process Builder can be used to send messages to a Chatter group or user.</description>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shipment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Shipments</relationshipLabel>
        <relationshipName>Shipments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EstimatedShipDate__c</fullName>
        <label>Estimated Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrderId__c</fullName>
        <label>Order ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingCity__c</fullName>
        <label>Shipping City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingPostalCode__c</fullName>
        <label>Shipping Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingState__c</fullName>
        <label>Shipping State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShippingStreet__c</fullName>
        <label>Shipping Street</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Shipment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShipmentPackage__c.object
<CustomObject>
    <fields>
        <fullName>Shipment__c</fullName>
        <label>Shipment</label>
        <referenceTo>Shipment__c</referenceTo>
        <relationshipName>ShipmentPackages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Unknown&quot;</defaultValue>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Shipment Package</label>
    <nameField>
        <label>ShipmentPackage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ShipmentDelegateTest.cls
/*******************************************************************************************************
* @description Test coveraage for ShipmentDelegate
* 
*/
@isTest (seeAlldata=false)
public with sharing class ShipmentDelegateTest {
    
    private static String orderNumber = '1234567890';

    @testSetup
    private static void setupData() {
        TestDataService.setupRestEnvironmentProperties();
        TestDataService.setupSlackCustomSettings();
        TestDataService.setupLoggingCustomSettings();
    }

    @isTest static void testHTTPResponse() { 
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ShipmentUpsMockHttpResponseGenerator(200, ShipmentUpsMockHttpResponseGenerator.REQUEST_TYPE.GET_SHIPMENT_TRACKING_INFO));
        ShipmentPackage__c p = ShipmentDelegate.GetShipmentTrackingInfo('UPS','1z2345678901');
        System.AssertEquals(p.Status__c, 'DELIVERED');
        Test.stopTest();
    }

    @isTest static void testCancelOrderUnknownStatusCode() {
   
        Test.startTest();
        String invalidResponseStatus= 'INVALID RESULT TEST 12345';

        Test.setMock(HttpCalloutMock.class, 
            new ShipmentUpsMockHttpResponseGenerator(200, 
                ShipmentUpsMockHttpResponseGenerator.REQUEST_TYPE.CANCEL_ORDER,
                '[{"Status" : "'+ invalidResponseStatus + '"}, {"OrderId" : "' + orderNumber + '"}]'));
        
        System.assertEquals(0, [SELECT Id FROM Exception_Log__c].size());

        HttpRequestResult requestResult = ShipmentDelegate.cancelOrder(orderNumber);
        
        System.assertEquals(false, requestResult.success, 'cancelOrder expected to fail.');

        Exception_Log__c exceptionLog = [SELECT Id, Message__c FROM Exception_Log__c limit 1][0];
        System.assertNotEquals(null, exceptionLog, 'Expected to have Exception_Log__c object inserted.');

        String exceptionMessage = (new Constants.ExceptionMessages().SHIPMENT_EXCEPTION_UNKNOWN_STATUS_CODE + '{Status=' + invalidResponseStatus + '}');
        System.assertEquals(exceptionMessage, exceptionLog.Message__c);
        
        Test.stopTest();
    }

    @isTest static void handleCancelOrderManualProcessTest () {

        Account account1 = new Account(Name = 'Test Account 123');
        insert account1;

        Shipment__c shipment1 = new Shipment__c(OrderId__c = orderNumber,
                                               Account__c = account1.Id,
                                               ShippingStreet__c = 'No Name Street 123',
                                               ShippingCity__c = 'Chicago',
                                               ShippingPostalCode__c = '60610',
                                               ShippingState__c = 'IL',
                                               EstimatedShipDate__c = Date.today()
                                            );
        insert shipment1;

        Test.startTest();

        String invalidResponseStatus= '';

        Test.setMock(HttpCalloutMock.class, 
            new ShipmentUpsMockHttpResponseGenerator(200, 
                ShipmentUpsMockHttpResponseGenerator.REQUEST_TYPE.CANCEL_ORDER,
                '[{"Status" : ""}, {"OrderId" : "' + orderNumber + '"}]'));
        
        System.assertEquals(0, [SELECT Id FROM Exception_Log__c].size());

        HttpRequestResult requestResult = ShipmentDelegate.cancelOrder(orderNumber);
        
        System.assertEquals(true, requestResult.success, 'cancelOrder expected to succeed.');

        Exception_Log__c exceptionLog = [SELECT Id, Message__c FROM Exception_Log__c limit 1][0];
        System.assertNotEquals(null, exceptionLog, 'Expected to have Exception_Log__c object inserted.');

        String exceptionMessage = (new Constants.ExceptionMessages().SHIPMENT_EXCEPTION_UNKNOWN_STATUS_CODE + ' OrderId: '+ orderNumber + ' canceled, but Status code return was blank!');
        System.assertEquals(exceptionMessage, exceptionLog.Message__c);
        
        Test.stopTest();
    }

    @isTest static void testCancelOrderNotFound() {

        Test.startTest();
        helperTestCancelOrderFailStatuses(ShipmentDelegate.NOT_FOUND, false);
        Test.stopTest();
    }

    @isTest static void testCancelOrderAlreadyProcessed() {

        Test.startTest();
        helperTestCancelOrderFailStatuses(ShipmentDelegate.ALREADY_PROCESSED, false);
        Test.stopTest();
    }

    @isTest static void testCancelOrderSuccesful() {

        Test.startTest();
        helperTestCancelOrderSuccessfulStatuses(ShipmentDelegate.CANCELLED, true);
        Test.stopTest();
    }

    @isTest static void testCancelOrderAlreadyCanceled() {

        Test.startTest();
        helperTestCancelOrderSuccessfulStatuses(ShipmentDelegate.ALREADY_CANCELED, true);
        Test.stopTest();
    }

    @isTest static void testCancelOrderStatusCode401() {
        Test.startTest();
        helperTestCancelOrderStatusCodes(401, false);
        Test.stopTest();
    }

    @isTest static void testCancelOrderStatusCode404() {
        Test.startTest();
        helperTestCancelOrderStatusCodes(404, false);
        Test.stopTest();
    }

    @isTest static void testCancelOrderStatusCode409() {
        Test.startTest();
        helperTestCancelOrderStatusCodes(409, false);
        Test.stopTest();
    }

    @isTest static void testCancelOrderStatusCode500() {
        Test.startTest();
        helperTestCancelOrderStatusCodes(500, false);
        Test.stopTest();
    }

    @isTest static void testCancelOrderStatusCode600() {
        Test.startTest();
        helperTestCancelOrderStatusCodes(600, false);
        Test.stopTest();
    }

    /*----------  Helper Methods Below this Line  ----------*/
    

    /*******************************************************************************************************
    * @description      Helper method to help test cover each status code in cancelOrder method
    * @param 
    * @param 
    * @return           void
    * 
    */
    static void helperTestCancelOrderStatusCodes(Integer statusCode, Boolean expectedToSucceed) {

        Test.setMock(HttpCalloutMock.class, 
            new ShipmentUpsMockHttpResponseGenerator(statusCode, 
                ShipmentUpsMockHttpResponseGenerator.REQUEST_TYPE.CANCEL_ORDER,
                '[{"Status" : "someStatus"}, {"OrderId" : "' + orderNumber + '"}]'));

        HttpRequestResult requestResult = ShipmentDelegate.cancelOrder(orderNumber);
        System.assertEquals(expectedToSucceed, requestResult.success);
    }

    /*******************************************************************************************************
    * @description     Helper test method to help with code duplicacy
    * 
    */
    static void helperTestCancelOrderSuccessfulStatuses(String shipmentDelegateStatus, Boolean expectedToSucceed) {

        Test.setMock(HttpCalloutMock.class, 
            new ShipmentUpsMockHttpResponseGenerator(200, 
                ShipmentUpsMockHttpResponseGenerator.REQUEST_TYPE.CANCEL_ORDER,
                '[{"Status" : "' + shipmentDelegateStatus + '"}, {"OrderId" : "' + orderNumber + '"}]'));

        HttpRequestResult requestResult = ShipmentDelegate.cancelOrder(orderNumber);
        System.assertEquals(true, requestResult.success);
    }

    /*******************************************************************************************************
    * @description     Helper test method to help with code duplicacy
    * 
    */
    static void helperTestCancelOrderFailStatuses(String shipmentDelegateStatus, Boolean expectedToSucceed) {

        Test.setMock(HttpCalloutMock.class, 
            new ShipmentUpsMockHttpResponseGenerator(200, 
                ShipmentUpsMockHttpResponseGenerator.REQUEST_TYPE.CANCEL_ORDER,
                '[{"Status" : "' + shipmentDelegateStatus + '"}, {"OrderId" : "' + orderNumber + '"}]'));
        
        System.assertEquals(0, [SELECT Id FROM Exception_Log__c].size());       
        HttpRequestResult requestResult = ShipmentDelegate.cancelOrder(orderNumber);   
        System.assertEquals(expectedToSucceed, requestResult.success);
        Exception_Log__c exceptionLog = [SELECT Id, Message__c FROM Exception_Log__c limit 1][0];
        System.assertNotEquals(null, exceptionLog, 'Expected to have Exception_Log__c object inserted.');
    }
}