src/objects/Exception_Log__c.object
<CustomObject>
    <description>Custom object used to store caught exceptions. Workflow rules can be leveraged to send email alerts upon record creation, and Process Builder can be used to send messages to a Chatter group or user.</description>
    <fields>
        <fullName>Line_Number__c</fullName>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type_Name__c</fullName>
        <label>Type Name</label>
        <picklist>
            <picklistValues>
                <fullName>AsyncException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CalloutException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DmlException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EmailException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>InvalidParameterValueException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LimitException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JSONException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ListException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MathException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NoAccessException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NoDataFoundException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NoSuchElementException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NullPointerException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QueryException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RequiredFeatureMissing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SearchException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SecurityException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SerializationException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SObjectException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>StringException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TypeException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VisualforceException</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>XmlException</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Exception Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LoggingServiceTest.cls
@isTest
public with sharing class LoggingServiceTest {
	private static testMethod void testGetMatchingLogs() {
    	Exception_Log__c existingLog1 = new Exception_Log__c(Level__c = new LoggingService.LoggingLevels().FATAL,
    														Line_Number__c = 808,
    														Trigger_Context__c = 'IsBefore: yes',
    														Type_Name__c = 'ListException');
    	insert existingLog1;

    	Exception_Log__c existingLog2 = new Exception_Log__c(Level__c = new LoggingService.LoggingLevels().INFO, // only difference is here
    														Line_Number__c = 808,
    														Trigger_Context__c = 'IsBefore: yes',
    														Type_Name__c = 'ListException');
    	insert existingLog2;

    	List<Exception_Log__c> matchingLogs = LoggingService.getMatchingLogs(new List<String>{'Id', 'Level__c', 'Line_Number__c', 'Trigger_Context__c', 'Type_Name__c'}, existingLog1);
    	System.assertEquals(existingLog1.Id, matchingLogs[0].Id, 'Matching Log Id expected to match Existing Log Id');
    	System.assertEquals(existingLog1.Level__c, matchingLogs[0].Level__c);
    	System.assertEquals(existingLog1.Line_Number__c, matchingLogs[0].Line_Number__c);
    	System.assertEquals(existingLog1.Trigger_Context__c, matchingLogs[0].Trigger_Context__c);
    	System.assertEquals(existingLog1.Type_Name__c, matchingLogs[0].Type_Name__c);
    }
}