src/objects/MediaChangeRequest__c.object
<CustomObject>
    <fields>
        <fullName>AgeInBusinessHours__c</fullName>
        <label>Age in Business Hours</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompletedDate__c</fullName>
        <description>Field used in a report and for Age calculation. DO NOT DELETE</description>
        <label>Completed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DateAssigned__c</fullName>
        <label>Date Assigned to Media</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Submit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by the clinic customizations UI to indicate that a change request should be immediately submitted for approval.</description>
        <label>Submit</label>
        <type>Checkbox</type>
    </fields>
    <label>Media Change Request</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MediaChangeRequestService.cls
public with sharing class MediaChangeRequestService {
	
	public static void submitRequests(List<MediaChangeRequest__c> requests) {
		List<Approval.ProcessSubmitRequest> approvalProcessRequests = new List<Approval.ProcessSubmitRequest>();
		for (MediaChangeRequest__c request : requests) {
			if (request.Submit__c) {
				Approval.ProcessSubmitRequest approvalProcessRequest = new Approval.ProcessSubmitRequest();
				approvalProcessRequest.setObjectId(request.Id);
				approvalProcessRequests.add(approvalProcessRequest);
			}
		}
		if (ListUtils.isNotNullOrEmpty(approvalProcessRequests)) {
			List<Approval.ProcessResult> results = Approval.process(approvalProcessRequests);
		}
	}

	public static void updateAge(List<MediaChangeRequest__c> requests, Map<Id, MediaChangeRequest__c> oldRequests) {
		BusinessHours hours = BusinessHoursService.getByName(new Constants.BusinessHours().MEDIA_BUSINESS_HOURS, new List<String>{'Id'});
		for (MediaChangeRequest__c request : requests) {
			if (request.CompletedDate__c != oldRequests.get(request.Id).CompletedDate__c && request.DateAssigned__c != null && request.CompletedDate__c != null) {
				request.AgeInBusinessHours__c = Decimal.valueOf(BusinessHours.diff(hours.Id, request.DateAssigned__c, request.CompletedDate__c)) / 3600000;
			}
		}
	}	
}