src/objects/MediaChangeRequest__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Media Change Requests</relationshipLabel>
        <relationshipName>MediaChangeRequests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AgeInBusinessHours__c</fullName>
        <label>Age in Business Hours</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CompletedDate__c</fullName>
        <description>Field used in a report and for Age calculation. DO NOT DELETE</description>
        <label>Completed Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DateAssigned__c</fullName>
        <label>Date Assigned to Media</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NeverExpires__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Never Expires</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used by the clinic customizations UI to indicate that a change request should be immediately submitted for approval.</description>
        <label>Submit</label>
        <type>Checkbox</type>
    </fields>
    <label>Media Change Request</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Media Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MediaChangeRequestTriggerTest.cls
@isTest
private class MediaChangeRequestTriggerTest {
	
	@isTest
	static void testMediaChangeRequestTrigger(){
		Account account = new Account();
		account.Name = 'Test Account';
		insert account;
		MediaChangeRequest__c request = new MediaChangeRequest__c();
		request.Account__c = account.Id;
		request.NeverExpires__c = true;
		request.Submit__c = true;
		request.Subject__c = 'Subject';
		insert request;
	}

	@isTest
	static void testUpdateAge_NullDateAssigned() {
		Account account = new Account(Name = 'Test Account');
		insert account;
		MediaChangeRequest__c request = new MediaChangeRequest__c(Account__c = account.Id,
																  NeverExpires__c = true,
																  Subject__c = 'Subject');
		insert request;

		request.CompletedDate__c = System.now();
		try {
			update request;
			system.assert([Select Id, AgeInBusinessHours__c From MediaChangeRequest__c Where Id =: request.Id].AgeInBusinessHours__c == null);
		}
		catch (DmlException ex) {
			system.assert(false);
		}
	}

	@isTest
	static void testUpdateAge() {
		Account account = new Account(Name = 'Test Account');
		insert account;
		MediaChangeRequest__c request = new MediaChangeRequest__c(Account__c = account.Id,
																  DateAssigned__c = System.now(),
																  NeverExpires__c = true,
																  Subject__c = 'Subject');
		insert request;

		request.CompletedDate__c = System.now();
		try {
			update request;
			system.assert([Select Id, AgeInBusinessHours__c From MediaChangeRequest__c Where Id =: request.Id].AgeInBusinessHours__c != null);
		}
		catch (DmlException ex) {
			system.assert(false);
		}
	}
}