src/objects/ProductionProperties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Production Environment Properties</label>
</CustomObject>

src/objects/StagingProperties__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to store endpoints for API integrations</description>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Staging Environment Properties</label>
</CustomObject>

src/classes/EnvironmentUtils.cls
public class EnvironmentUtils {

	public static String getEnvironmentProperty(String key) {
		if (UserInfo.getOrganizationId() == new Constants.OrganizationIds().PRODUCTION_ID) {
			Map<String, ProductionProperties__c> productionProperties = ProductionProperties__c.getAll();
			return productionProperties.get(key).Value__c;
		}
		else {
			Map<String, StagingProperties__c> stagingProperties = StagingProperties__c.getAll();
			return stagingProperties.get(key).Value__c;
		}
	}
}