src/objects/ShipmentPackage__c.object
<CustomObject>
    <fields>
        <fullName>RequestedDateOfArrivalExt__c</fullName>
        <formula>Shipment__r.RequestedDateOfArrival__c+5</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Requested Date Of Arrival Extention</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Unknown&quot;</defaultValue>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrackingNumber__c</fullName>
        <label>TrackingNumber</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Shipment Package</label>
    <nameField>
        <label>ShipmentPackage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ShipmentTrackingBatchScheduler.cls
global with sharing class ShipmentTrackingBatchScheduler implements Schedulable {
	global void execute(SchedulableContext sc) {				
		String query = (new SoqlBuilder()
                .selectx(new List<String> {'Id','Status__C', 'TrackingNumber__c'})
                .fromx('Shipmentpackage__c')
                .wherex(new AndCondition()
                        .add (new FieldCondition('Status__C').notequals('DELIVERED'))
                        .add (new FieldCondition('RequestedDateOfArrivalExt__C ').greaterThanOrEqualTo(new DateFormula().todayx()))
                       ).toSoql()); 
		ShipmentTrackingBatch colBatch = new ShipmentTrackingBatch(query);			 
		Id batchprocessid = Database.executeBatch(colBatch,1);		   	
	}
}