src/objects/ShipmentPackage__c.object
<CustomObject>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <label>Activity Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LeftAtLocation__c</fullName>
        <label>Left at Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScheduledDeliveryDate__c</fullName>
        <label>Scheduled Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SignedForName__c</fullName>
        <label>Signed For Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Unknown&quot;</defaultValue>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TrackingNumber__c</fullName>
        <label>TrackingNumber</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Shipment Package</label>
    <nameField>
        <label>ShipmentPackage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ShipmentTrackingBatch.cls
Global  with sharing class ShipmentTrackingBatch implements Database.Batchable<SObject>, Database.AllowsCallouts
{

  global final String Query;
      global ShipmentTrackingBatch(string q){       
        this.query = q;
      }

      global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
      }
    
     global void execute(Database.BatchableContext BC, List<ShipmentPackage__c>scope){
          List <ShipmentPackage__c> ShipmentPkgToUpdate = new list <ShipmentPackage__c>();
          for (ShipmentPackage__c pkg : scope){
              
              ShipmentPackage__c p = ShipmentDelegate.GetShipmentTrackingInfo('UPS', pkg.TrackingNumber__c); 
              if (p.Status__c<> null){pkg.Status__C  = p.Status__c.toUpperCase();}
              pkg.ActivityDate__c = p.ActivityDate__c;
              pkg.LeftAtLocation__c = p.LeftAtLocation__c;
              pkg.SignedForName__c = p.SignedForName__c;
              if (p.ScheduledDeliveryDate__c != null){
               pkg.ScheduledDeliveryDate__c = p.ScheduledDeliveryDate__c;
              }

              ShipmentPkgToUpdate.add(pkg);
            } 
            
            update(ShipmentPkgToUpdate);
     }
   
     global void finish(Database.BatchableContext BC){
         
     }
}